### ISSUE TITLE
Setting "hidden={true}" in Button and IconButton components has no effect

### ISSUE THREAD

**Issue by bluescr33nofdeath** [creativetimofficial/material-tailwind#105]
In React, if I set a Button or IconButton with "hidden={true}", it still appears. Removing the class "inline-block" they use solves that issue.

![imagen](https://user-images.githubusercontent.com/106739022/171606074-a4d389c5-5b53-4489-9971-7ed626feaade.png)

**Comment by sajadevo** [comment]
Hi @bluescr33nofdeath,

Thanks for letting me know about this issue, I've updated the product and now it's working fine and the hidden attribute is working.

All the best,
Sajad
