### ISSUE TITLE
Accordian change default collapse/expaln icon

### ISSUE THREAD

**Issue by nimatrazmjo** [creativetimofficial/material-tailwind#108]
Is there any way to chnage collapse/explan icon from `+/-` to  drop down like  arrow up and down icon 

Thanks

**Comment by sajadevo** [comment]
HI @nimatrazmjo,

Yup you can just check the props information for the Accordion you can pass the icon prop and add the icon you like to have.
[Accordion Props](https://www.material-tailwind.com/docs/react/accordion#accordion-props)

All the best,
Sajad
