### ISSUE TITLE
material-tailwind.js missing on @material-tailwind/html

### ISSUE THREAD

**Issue by murunwas** [creativetimofficial/material-tailwind#113]
I  installed @material-tailwind/html but I can't find the **material-tailwind.js** mention on the documentation.

**Comment by oren1991** [comment]
Hi @murunwas! ran into same issue I think the docs are not updated. Checked the react docs and based on that I could figure it out
```js
const withMT = require("@material-tailwind/html/utils/withMT");

module.exports = withMT({
  content: ['./js/**/*.js', '../lib/*_web/**/*.*ex'], // this is an example
  theme: {
    extend: {},
  },
  plugins: [],
})

```
The idea is to wrap your tailwind config with the withMT util thingy :)

**Comment by oren1991** [comment]
hi @murunwas a possible workaround: 
download it from `public/material-tailwind-html.js`

but I guess it would be nice if it was there with the package itself :)

**Comment by oren1991** [comment]
Hi @sajadevo 

is it okay if the build of the html package included the js file?

```js
// material-tailwind-html/package.json
{
...
  "build": "mkdir dist && cp -r ./theme ./dist/theme && cp -r ./utils ./dist && cp package.json ./dist && cp ./README.md ./dist && cp ./LICENSE ./dist && cp ../../public/material-tailwind-html.js ./dist",
...
}


```

**Comment by sajadevo** [comment]
@oren1991,

Sure it can, I already fixed this issue within an hour a new version will be available with the new docs update for html version.

All the best,
Sajad

**Comment by sajadevo** [comment]
Hi guys, 

The new version is released please check the change log there: [@material-tailwind/html v1.1.2](https://github.com/creativetimofficial/material-tailwind/releases/tag/1.1.2)

All the best,
Sajad
