### ISSUE TITLE
Dialog and few other components not working

### ISSUE THREAD

**Issue by ashfahan** [creativetimofficial/material-tailwind#114]
i just created a fresh project to test out material tailwind few of the components (like buttons) worked but as soon as i add dialog component from example it throws this error

i was using react 18 project with typescript

![image](https://user-images.githubusercontent.com/19289015/174460232-70c2492e-33b6-431a-b8e0-c66e3886dac1.png)

**Comment by ignaciojcano** [comment]
Rolled back to 1.0.3 and it works there

**Comment by sajadevo** [comment]
Hi @ashfahan,

I've tested the project and it's an issue with the CRA based applications and I will fix it very soon.

All the best,
Sajad
