### ISSUE TITLE
Question: How to keep tailwindcss default colors

### ISSUE THREAD

**Issue by Rango-dz** [creativetimofficial/material-tailwind#115]
Hi,

After i installed material-tailwind i noticed a change in colors name and colors themselves , how can i keep tailwind default colors instead ?

thank you

**Comment by sajadevo** [comment]
Hi @Rango-dz,

Just import the tailwindcss color and and add the color you like to have.

```js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    colors: {
     blue: colors.blue,
    },
  },
}
```

All the best,
Sajad
