### ISSUE TITLE
Checkbox and Inputs cannot be controlled

### ISSUE THREAD

**Issue by rolandin** [creativetimofficial/material-tailwind#116]
I appologize in advance if I don't understand exactly how is supposed to be done or couldn't find the proper solution in the docs, feel free to close issue with an answer or a link, but I don't think the input  and checkbox components have props to be controlled, the input doesnt have a `value` prop nor the checkbox has a `checked` prop. 

Any ways to control them? 
There is neither a prop to pass `{ ...props }` to the inside component as they often are wrapped in a div or a label inside a div, how would we go about this?

**Comment by sajadevo** [comment]
Hi @rolandin,

The Input and Checkbox components are working as native html components and you can make them controlled as you're doing it for native html components in react, here is a example for both Input and Checkbox components.

**Input**
```jsx
import { useState } from "react";
import { Input } from "@material-tailwind/react";

export default function Example() {
  const [value, setValue] = useState("");

  return (
    <Input
      label="Username"
      onChange={(e) => setValue(e.target.value)}
      value={value}
    />
  );
}
```

**Checkbox**
```jsx
import { useState } from "react";
import { Checkbox } from "@material-tailwind/react";

export default function Example() {
  const [checked, setChecked] = useState(false);

  return <Checkbox checked={checked} onChange={() => setChecked(!checked)} />;
}
```

All the best,
Sajad

**Comment by rolandin** [comment]
@sajadevo  Affirmative!  I apologize, not sure what I was doing wrong.
Thanks for your hard work! The library is beautiful I love it!

**Comment by sr-tamim** [comment]
I was trying to get input value using _useRef_ hook in react but I couldn't do that.
@sajadevo Your method is working perfectly, **Thank you!**
#### However, is there any way to get value using _useRef_ hook?

**Comment by sajadevo** [comment]
> I was trying to get input value using _useRef_ hook in react but I couldn't do that. @sajadevo Your method is working perfectly, **Thank you!**
> 
> #### However, is there any way to get value using _useRef_ hook?

Hi @sr-tamim,

Here is the code example based on your situation.

```jsx
import { useRef, useState, useEffect } from "react";
import { Input } from "@material-tailwind/react";

export default function Example() {
  const inputRef = useRef(null);
  const [value, setValue] = useState("");

  useEffect(() => {
    console.log(inputRef.current.firstChild.value);
  }, [value]);

  return (
    <Input
      ref={inputRef}
      label="Example"
      value={value}
      onChange={(e) => setValue(e.currentTarget.value)}
    />
  );
}
```

Cheers,
Sajad

**Comment by eByte23** [comment]
Sorry to comment on a closed issue here.
Would a pr be accepted that adds the ability to pass `inputRef` which is the ref for the input field it's self so that the inputs ref can be accessed directly.

Material ui also does this.
See [https://mui.com/material-ui/api/input/#props](https://mui.com/material-ui/api/input/#props) `inputRef`
Thanks.

**Comment by sajadevo** [comment]
Hi @eByte23,

Thanks for your suggestion we're trying to make the library better day by day, I'll add this feature on the next update.

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey @eByte23 and @rolandin,

This issue is fixed and now you can pass an inputRef prop for the input. Update to v1.2.5

Cheers,
Sajad
