### ISSUE TITLE
TypeError: (0 , _reactDomInteractions).offset is not a function

### ISSUE THREAD

**Issue by 1OfThose** [creativetimofficial/material-tailwind#123]
Trying to use a Select input and its relative Option tags (even if simply using the example from the docs) doesn't work and gives this error (React 18+) : 

`Uncaught TypeError: (0 , _reactDomInteractions).offset is not a function`

**Comment by sajadevo** [comment]
Hi @1OfThose,

Please update to the latest version of @material-tailwind/react (v1.0.6), I already fix this issue.

All the best,
Sajad
