### ISSUE TITLE
Change default style of components

### ISSUE THREAD

**Issue by Kilian-mescam** [creativetimofficial/material-tailwind#141]
It says that I can change default style of each component

https://www.material-tailwind.com/docs/react/theming

"The theme object is a plain object that contains all of the components styles object. All of the components styles are available in the theme object and these styles object has a unique format for different use cases."

But I don't understand where to put this object (which file ? should I call it ?)
How to customize it ?

For example, if I want to customize a button, Should I do like this ? : 

```
themeObject = {
    componentTheme = {
      Button: {
        defaultProps: { },
        valid: { },
        styles: { 
          "bg-red-300"
         }
      },
    },
```
    Thank you for your help
    
    Kilian

**Comment by lansolo99** [comment]
I would be interested to get a working example also, as the documentation is lacking too much informations on theming...

**Comment by sajadevo** [comment]
Hi @lansolo99, @Kilian-mescam,

I'm working on the styling part for the documentation to add the styling guide for each component and it will be available soon.

All the best,
Sajad
