### ISSUE TITLE
Misleading content on Next.js integration documentation

### ISSUE THREAD

**Issue by lansolo99** [creativetimofficial/material-tailwind#142]
Nothing big, but this sentence regarding the TailwindCSS configuration snippet for the [next documentation](https://www.material-tailwind.com/docs/react/guide/next) misleaded me : 
```
On the pages/_app.js or pages/_app.tsx if you're using typescript put the code bellow.
```
This snippet has to be put inside tailwind.config.js, otherwise we get the following error : 
```
The default export is not a React Component in page: "/_app"
```

The best would be to clearly point at this file. 

Thanks for this very useful lib by the way 👍

**Comment by sajadevo** [comment]
Hi @lansolo99,

Thanks for letting us know we're building the documentation day by day and trying to complete it the best possible way.

All the best,
Sajad
