### ISSUE TITLE
Icon button is not able to get the Icons

### ISSUE THREAD

**Issue by satish860** [creativetimofficial/material-tailwind#143]
I am working on Next JS and trying to add an Icon to my page. I started with an example given on the page

```
import { Button, IconButton } from "@material-tailwind/react";
import React from "react";

const Header = () => {
  return (
    <div
      className="flex items-center sticky top-0 
    z-50 px-4 py-4 shadow-md bg-white"
    >
      <IconButton>
        <i className="fas fa-heart"></i>
      </IconButton>
      <h1>Docs</h1>
    </div>
  );
};

export default Header;
```
Do I need to add any dependencies or Am I missing any obvious reference? I added font awesome but it did not help.

**Comment by sajadevo** [comment]
Hi @satish860,

Which version of the fontawesome you've added to your project?

All the best,
Sajad

**Comment by satish860** [comment]
Hi Sajad, Added 6.0 version

**Comment by sajadevo** [comment]
@satish860,

The v6 is a bit different add this one: `<i className="fa-solid fa-heart" />`

All the best,
Sajad

**Comment by slhck** [comment]
> Which version of the fontawesome you've added to your project?

Do users have to install something manually here?

I do not see any mention of this in the installation instructions or on this page: https://www.material-tailwind.com/docs/react/icon-button

I also have the same problem, my icon is not showing:

```
<i class="fas fa-heart"></i>
```

<img width="70" alt="image" src="https://user-images.githubusercontent.com/582444/191447810-2d215d15-3448-4a54-84cd-de53e1b547ce.png">

**Comment by sajadevo** [comment]
Hi @slhck,

You need to add the font awesome cdn link to your project to use font awesome icons.

Cheers,
Sajad

**Comment by slhck** [comment]
I see. Is this documented anywhere? If not, please add it to the installation instructions, e.g. here:

- https://www.material-tailwind.com/docs/react/installation
- https://www.material-tailwind.com/docs/react/icon-button

**Comment by slhck** [comment]
Any updates on this? It would be nice to have instructions or best-practice suggestions on how to add the CDN. Given that this projects offers first-class support, it should really be documented to avoid confusion. Thanks!

**Comment by sajadevo** [comment]
Hey @slhck,

I'll add it on the next update until use the following link for the cdn of [fontawesome](https://cdnjs.com/libraries/font-awesome)

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey Guys,

This issue is fixed, I've a section related to font-awesome and how to add other icon libraries cdn.
Cheers,
Sajad
