### ISSUE TITLE
Handle disabled attribute

### ISSUE THREAD

**Issue by pizzafroide** [creativetimofficial/material-tailwind#144]
When the `disabled` attribute is added to a `Button` for example, its style currently does not change at all.

From MaterialUI documentation:
![React Button component - Material UI - Google Chrome](https://user-images.githubusercontent.com/7723814/177528806-943a1914-ffec-4b7b-a00a-70c0335326d4.png)

It could also be done for `Input`, `Radio`, `Select`, `Switch`, and `Textarea`.

**Comment by mrkirchner** [comment]
this would be amazing

**Comment by sajadevo** [comment]
Hi guys, 

The issues is fixed on the `@material-tailwind/react-v1.1.0`.

Cheers,
Sajad
