### ISSUE TITLE
Switch not showing correctly

### ISSUE THREAD

**Issue by mnonga** [creativetimofficial/material-tailwind#146]
I'm using  "@material-tailwind/react": "^1.0.6", and  "tailwindcss": "^3.0.24", in a react typescript project.

**Comment by sajadevo** [comment]
Hi @mnonga,

Thanks for using material-tailwind, could you please send me a screenshot?

Regards,
Sajad

**Comment by mnonga** [comment]
> Hi @mnonga,
> 
> Thanks for using material-tailwind, could you please send me a screenshot?
> 
> Regards, Sajad

![image](https://user-images.githubusercontent.com/51037169/177959615-bb2ed44b-1d8f-4658-a5d1-e4bc186d894c.png)

**Comment by egalindoEH** [comment]
This is my code and looks like this: 
`<div className='bg-yellow-400 w-full'>
                                <Switch defaultChecked />
                            </div>`

Versions:
"@material-tailwind/react": "^1.2.3",
"tailwindcss": "^3.1.8"

![image](https://user-images.githubusercontent.com/108294256/188372230-946a8a94-25d6-43c8-b16f-0b0b61658299.png)

**Comment by sajadevo** [comment]
Hey guys,

I've tested the `<Switch />` component and it's working fine, please update to the latest version `v1.2.4` and also follow the guide for [installing and using @material-tailwind/react](https://www.material-tailwind.com/docs/react/installation)

Cheers,
Sajad
