### ISSUE TITLE
Select component not showing correctly

### ISSUE THREAD

**Issue by illiyyin** [creativetimofficial/material-tailwind#147]
I just browse the page, and I found this 
![Screenshot (8)](https://user-images.githubusercontent.com/42526534/177910126-d84717fb-b375-40d0-887e-8e821ee955a7.png)
![Screenshot (10)](https://user-images.githubusercontent.com/42526534/177910301-87e3b8d7-1ea9-4174-bf51-0f6e57ac9cd5.png)

on page https://www.material-tailwind.com/docs/react/select

**Comment by sajadevo** [comment]
Hi @illiyyin,

Thanks for reporting this issue I will fix.

Regards,
Sajad

**Comment by sajadevo** [comment]
> can you document how to use onChange on this?!? doesn't work, I tried for a while.

Hi @tan-ahmed,

The `Select` component `onChange` prop works together with the `value` props of the `Option` here is a quick example:

```jsx
<Select
  label="Select Version"
  onChange={(value) => console.log(value)}
>
  <Option value="html">Material Tailwind HTML</Option>
  <Option value="react">Material Tailwind React</Option>
  <Option value="vue">Material Tailwind Vue</Option>
  <Option value="angular">Material Tailwind Angular</Option>
  <Option value="svelte">Material Tailwind Svelte</Option>
</Select>
```

Cheers,
Sajad

**Comment by huuhieu17** [comment]
![image](https://user-images.githubusercontent.com/31349335/181617243-5fce2753-d1c4-48f4-b9c1-c35cc41673b3.png) 
select not show selected dynamic data
![image](https://user-images.githubusercontent.com/31349335/181617452-7cb05845-c606-4fa1-82d2-120818a77960.png)

**Comment by huuhieu17** [comment]
**select not show selected dynamic data**
![image](https://user-images.githubusercontent.com/31349335/181617243-5fce2753-d1c4-48f4-b9c1-c35cc41673b3.png) 

` <div className=" ">
            <Select color="purple" label="Năm"

              onChange={(e) => searchData(e, "year")}
            >
              <Option value="0">Tất cả</Option>
              {listYear?.map((item, index) =>
              (
                <Option key={item} value={item}>Năm {item}</Option>
              )
              )}
            </Select>
          </div>`

**Comment by illiyyin** [comment]
@huuhieu17 you forgot `value` props
