### ISSUE TITLE
How to change border color of inputs

### ISSUE THREAD

**Issue by nickfthedev** [creativetimofficial/material-tailwind#151]
Can't figure it out, also can't change color of checkbox. Can someone help me?

**Comment by sajadevo** [comment]
Hi @unchainedDev,

Which version of the library you're using the react or html?

Cheers,
Sajad

**Comment by unchainedDev** [comment]
Sorry forgot to mention I am using the html version

**Comment by MadhuSaini22** [comment]
How can we change the border- color of input type ="text" on focus?
Can anyone tell me as I'm new in tailwind

**Comment by groovemen** [comment]
Hello @MadhuSaini22,

Thank you for using our products, for now, you have to change the component styling to achieve that. We will implement into future updates a feature to easily change the input border color. 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by Kilian-mescam** [comment]
Hello,

is this new feature available ? i don't understand how I can change the styling of the component to change color on focus. 
PS: I'm working on react

thanks
Kilian

**Comment by jonandgon** [comment]
Any updates? Default red color does not work for my theme.

**Comment by sajadevo** [comment]
Hey guys,

I've released a new update of the library and now it's using pure tailwind css classes for everything rather than custom classes so now it's easy to customise the styles of components.

Cheers,
Sajad
