### ISSUE TITLE
material-tailwind not working in nextjs

### ISSUE THREAD

**Issue by sr-tamim** [creativetimofficial/material-tailwind#152]
### As you can see that button isn't styled as expected.

![image](https://user-images.githubusercontent.com/86656406/179389985-6b5b9c3a-13fb-44c6-845a-133bf4c8d91f.png)

----

### See the code:
![image](https://user-images.githubusercontent.com/86656406/179390203-5f2ef8a9-2d33-4369-8a28-75c6709a7fe0.png)

**Comment by sajadevo** [comment]
Hi @sr-tamim,

You've missed to install tailwindcss because the styles are coming from tailwindcss library. Here is the docs for installing taillwindcss with next.js [TailwindCSS NextJS](https://tailwindcss.com/docs/guides/nextjs)

Cheers,
Sajad

**Comment by sr-tamim** [comment]
Oh, okay. I didn't noticed that.
**Thanks for your help**
