### ISSUE TITLE
add readme instruction for locally serving the documentation

### ISSUE THREAD

**Issue by c-nv-s** [creativetimofficial/material-tailwind#153]
Please could you add a note to the readme on how to serve the documentation locally for when users are offline

**Comment by tan-ahmed** [comment]
overal docs need to be improved, they don't explain how to use any of the components.  we need examples, even if its a codesandbox example on each page...

**Comment by sajadevo** [comment]
Hi @tan-ahmed,

I'm working on this part to add variety of examples for each docs page.

Cheers,
Sajad
