### ISSUE TITLE
Attempted import error: 'Typography'

### ISSUE THREAD

**Issue by oyamo** [creativetimofficial/material-tailwind#156]
Tried to import typography using ` import { Typography } from "@material-tailwind/react";` 
I got the following error 
`./src/components/ProductCard.js
Attempted import error: 'Typography' is not exported from '@material-tailwind/react'.`
I am using version `0.3.4`

**Comment by sajadevo** [comment]
Hi @oyamo,

Please update @material-tailwind/react to the latest version.

Cheers,
Sajad
