### ISSUE TITLE
Limited Background Colours are available (Materials Tailwind + Next.js + React)

### ISSUE THREAD

**Issue by UBCToad** [creativetimofficial/material-tailwind#168]
Hi,
I'm new to Material Tailwind, Tailwind CSS, Node.js and everything React, so it's possible I'm doing something wrong.

In the ThemeProvider configuration object, for a tooltip I can set the background colour to bg-yellow-500 but not bg-yellow-300, etc.  Only 500.  (although blue-grey can be 500, 100, or 50)

Should this be possible?
From what I understand the following colour pallet should be supported:
https://www.material-tailwind.com/docs/react/colors
or
https://tailwindcss.com/docs/background-color
or both?

Below is reproducing steps.  I'm happy to help out if investigation is needed.

The relevant file is `config/materials_tailwind.js` here.  Steps to reproduce follow.
```
export const MATERIALS_TAILWIND_THEME = {
  button: {
    defaultProps: {
      className: 'w-fit',
      color: 'green',
    },   
  },      
  tooltip: {
    styles: {
      base: {
        bg: 'bg-yellow-500',
        text: 'text-green-500',
        width: 'max-w-md',
      },
    },
  },
}
```

Create a new Tailwind CSS/Next.js application:
```
https://tailwindcss.com/docs/guides/nextjs
npx create-next-app my-project
cd my-project
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
```

I also installed:
```
npm install -D prettier-plugin-tailwindcss @material-tailwind/react
```

Add Tailwind to `./styles/globals.css`:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Add material tailwind hooks:
```
tailwind.config.js
const withMT = require("@material-tailwind/react/utils/withMT")

module.exports = withMT({
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    fontFamily: {
      quicksand: 'Quicksand, sans-serif',
      inter: 'Inter, sans-serif',
    },
    extend: {
    },
  },
  plugins: [],
})
```

```
pages/_app.js
import '../styles/globals.css'
import { ThemeProvider } from '@material-tailwind/react';
import { MATERIALS_TAILWIND_THEME } from '../config/materials_tailwind';

export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider value={MATERIALS_TAILWIND_THEME}>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}
```

```
config/materials_tailwind.js (Shown above)
```

```
pages/index.js
import { Button } from "@material-tailwind/react";
import { Tooltip } from "@material-tailwind/react";
...
        <div className='mx-auto max-w-6xl px-4 pt-16 text-center text-gray-900'>
          <h1 className='mx-auto max-w-6xl px-4 pt-16 text-center text-4xl text-gray-900'>
            Welcome to Tailwind CSS!
          </h1>

          <Tooltip content='This is a test tooltip!'>
            <Button>Continue</Button>
          </Tooltip>
        </div>
...
```

With bg-yellow-500 the tooltip background is yellow.  With bg-yellow-300 the tooltip background is transparent.
Thanks.

**Comment by UBCToad** [comment]
As a workaround, I found that adding a className directly to the component invocation will accept any colours:
```
components/CustomTooltip.jsx:
import { Tooltip } from '@material-tailwind/react'

export default function CustomTooltip({ content, children }) {
  if (!content) return children;

  return (
    <Tooltip className='bg-yellow-300' content={content}>
      {children}
    </Tooltip>
  )
}
```
This has been working well for all the components and even custom defined colours.

**Comment by sajadevo** [comment]
Hi @UBCToad,

The color props for component are only getting the 500 color code but if you wish to have more you can use `className` prop the `classNam` prop is available for all components and it will help you for customizing the components. For the future update we will try to have a prop `level` for defining the color level of component, e.g. 
`<Tooltop color="yellow" level="300" />`

Cheers,
Sajad
