### ISSUE TITLE
Custom Tabs and New Features

### ISSUE THREAD

**Issue by shakibdshy** [creativetimofficial/material-tailwind#175]
I'm New in this field and am now practicing React and Typescript with a material tailwind.  
There are no options are available to change the Active TabsHeader white background color.

![image](https://user-images.githubusercontent.com/15661765/181460215-e2e6bbce-4b1f-4744-99e1-47009c9afcc2.png)

 I'm trying to build a custom Tabs Style but I think the Documentation didn't provide more specific information.   Like This screenshot, You provided `Code` but how do use it you didn't provide it.

![image](https://user-images.githubusercontent.com/15661765/181444033-ff76f644-6974-498e-ab90-6e9a511bd906.png)

Also, I think You can add More Features Like `Vertical Tabs`, ` Color`,  `Size`, `Active Tabs Header Style`

**Comment by sajadevo** [comment]
Hi @shakibdshy,

Sure we'll add more examples but it needs time we're doing everything step by step, for now you can use the following link for the [tabs indicator](https://www.material-tailwind.com/docs/react/theme/tabs#tab-theme-object-type) styling.

Cheers,
Sajad

**Comment by shakibdshy** [comment]
```
const theme = {
  tabsHeader: {
    styles: {
      base: {
        display: "flex",
        position: "relative",
      },
    },
  },
};
```
@sajadevo Can please tell me how to use this code and where can I add this code? 
Please give me a live example.

**Comment by sajadevo** [comment]
@shakibdshy please take a look to this page: [Material Tailwind Theming Guide](https://www.material-tailwind.com/docs/react/theming).

Cheers,
Sajad
