### ISSUE TITLE
Is it possible to use this with SvelteKit?

### ISSUE THREAD

**Issue by esphoenixc** [creativetimofficial/material-tailwind#190]
Is it possible to use this with SvelteKit? I know it's compatible with REACt, but can I use with SvelteKit + Vite?

**Comment by sajadevo** [comment]
Hi @esphoenixc,

Unfortunately you can't use it with SvelteKit at the moment this library is only available for HTML and React but you can use the HTML version in the SvelteKit because the `@material-tailwind/html` is working only with tailwindcss it's build for general usage.

Cheers,
Sajad
