### ISSUE TITLE
Change color of Input focus

### ISSUE THREAD

**Issue by joaoperigo** [creativetimofficial/material-tailwind#192]
Hello! I Can't change color of Input focus. And didn't find a documentation.  I want to use tailwind colors, beside the limited colors in Materials. 

### The ideal should be, wenever I want to set a color, from tailwind.config theme:
`<Input label="Username" color="black-1"  />`

### I get a results trying this (not ideal):
I achieved to change color in global.css:
```
  label {
    @apply  peer-focus:text-black-1  peer-focus:before:border-black-1 peer-focus:after:border-black-1 !important;
  }
```

And added the tailwind theme color in the className:
`<Input label="Username" className="focus:border-black-1"  />`

#### But when I did that only work with one color, I tryed to add another selector:
```
  .black-1 label {
    @apply  peer-focus:text-black-1  peer-focus:before:border-black-1 peer-focus:after:border-black-1 !important;
  }
```

And in the component:
```
  <div className="w-72 black-1">
    <Input label="Username" className="focus:border-black-1"  />
  </div>
```

I need two input colors, from tailwind, and ThemeProvider is to complex, and didn't find documentation

**Comment by sajadevo** [comment]
Hi @joaoperigo,

Please follow this page: [https://www.material-tailwind.com/docs/react/theme/input](https://www.material-tailwind.com/docs/react/theme/input)

Cheers,
Sajad
