### ISSUE TITLE
MobileNav Doesn't work in next js.

### ISSUE THREAD

**Issue by DavidRamirez92** [creativetimofficial/material-tailwind#193]
When I use the component Navbar response ok on large screens, but on mobile, when you click on the burger icon, doesn't open the menu. I think the problem is with the Component <MobileNav>
I tested the example code at https://www.material-tailwind.com/docs/react/navbar 
I probed in Chrome and in Edge.
I Attach images with the problem.
![open menu](https://user-images.githubusercontent.com/62220834/182979609-e145f04f-94c2-4ad5-a0f0-8efb56079cc8.png)
![without open the menu](https://user-images.githubusercontent.com/62220834/182979612-49e62773-f4c1-43e8-9ed1-24ca26771dbd.png)

that's all.
I await your response.
best regards

**Comment by sajadevo** [comment]
Hi @DavidRamirez92,

Please share the navbar code with me.

Cheers,
Sajad

**Comment by DavidRamirez92** [comment]
Sajad, Nice to meet you.
I send you the code Below:

import { useState, useEffect } from "react";
import {
  Navbar,
  MobileNav,
  Typography,
  Button,
  IconButton,
} from ***@***.***/react";

export default function Test() {
  const [openNav, setOpenNav] = useState(false);

  useEffect(() => {
    window.addEventListener(
      "resize",
      () => window.innerWidth >= 960 && setOpenNav(false)
    );
  }, []);

  const navList = (
    <ul className="mb-4 mt-2 flex flex-col gap-2 lg:mb-0 lg:mt-0
lg:flex-row lg:items-center lg:gap-6">
      <Typography as="li" variant="small" className="p-1 font-normal">
        <a href="#" className="flex items-center">
          Pages
        </a>
      </Typography>
      <Typography as="li" variant="small" className="p-1 font-normal">
        <a href="#" className="flex items-center">
          Account
        </a>
      </Typography>
      <Typography as="li" variant="small" className="p-1 font-normal">
        <a href="#" className="flex items-center">
          Blocks
        </a>
      </Typography>
      <Typography as="li" variant="small" className="p-1 font-normal">
        <a href="#" className="flex items-center">
          Docs
        </a>
      </Typography>
    </ul>
  );

  return (
    <Navbar className="mx-auto max-w-screen-xl py-2 px-4 lg:px-8 lg:py-4">
      <div className="container mx-auto flex items-center justify-between
text-blue-gray-900">
        <Typography
          as="a"
          href="#"
          variant="small"
          className="mr-4 cursor-pointer py-1.5 font-normal"
        >
          <span>Material Tailwind</span>
        </Typography>
        <div className="hidden lg:block">{navList}</div>
        <Button variant="gradient" size="sm" className="hidden
lg:inline-block">
          <span>Buy Now</span>
        </Button>
        <IconButton
          variant="text"
          className="ml-auto h-6 w-6 text-inherit hover:bg-transparent
focus:bg-transparent active:bg-transparent lg:hidden"
          ripple={false}
          onClick={() => setOpenNav(!openNav)}
        >
          {openNav ? (
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              className="h-6 w-6"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          ) : (
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M4 6h16M4 12h16M4 18h16"
              />
            </svg>
          )}
        </IconButton>
      </div>
      <MobileNav open={openNav}>
        {navList}
        <Button variant="gradient" size="sm" fullWidth className="mb-2">
          <span>Buy Now</span>
        </Button>
      </MobileNav>
    </Navbar>
  );
}

**Comment by Stargazer87** [comment]
> When I use the component Navbar response ok on large screens, but on mobile, when you click on the burger icon, doesn't open the menu. I think the problem is with the Component

I have the same problem

**Comment by sajadevo** [comment]
Hi guys,

The issue is fixed please update to `@material-tailwind/react/v1.2.3`.

Cheers,
Sajad

**Comment by DavidRamirez92** [comment]
Thank you so much Sajad.
Have a nice day.

**Comment by rashedpaykary** [comment]
Use <Collapse> instead of <MobileNav>
This is how it was fixed for me

**Comment by rashedpaykary** [comment]
Use <Collapse> instead of <MobileNav>
This is how it was fixed for me

**Comment by rashedpaykary** [comment]
Use Collapse instead of MobileNav
This is how it was fixed for me
