### ISSUE TITLE
Checkbox color not working

### ISSUE THREAD

**Issue by Nicki-Di** [creativetimofficial/material-tailwind#195]
despite changing the checkbox colour through the colour prop, the colour won't apply immediately and applies after defocusing the checkbox.

**Comment by sajadevo** [comment]
Hi @Nicki-Di,

Could you send me a short video of that issue?

Cheers,
Sajad

**Comment by pyskywalker** [comment]
https://user-images.githubusercontent.com/79524205/186229605-07b07c91-c620-4f9e-8e57-a3414b9af95b.mp4

**Comment by sajadevo** [comment]
Hi guys,

I'm closing this issue as it's not the library issue it's something with the computer and it's performance itself.

Cheers,
Sajad
