### ISSUE TITLE
Input label ins't activated on autofill

### ISSUE THREAD

**Issue by miriti** [creativetimofficial/material-tailwind#197]
material-tailwind version: 1.2.3 React

The "Passowrd" input:
![image](https://user-images.githubusercontent.com/1500502/184397468-55775ca1-52c1-490a-8cfe-6894536050d1.png)

It's getting fixed on any user's action on the page. If I, say, click anywhere on the page the label moves up. Not sure if it's a `material-tailwind` bug but any ideas on how to fix it?

**Comment by sajadevo** [comment]
Hi @miriti,

Probably you have some issue with implementing the input type password here is how you can do it:
```js
<Input type="password" label="Password" />
```

Cheers,
Sajad
