### ISSUE TITLE
tabs not support form inputs 

### ISSUE THREAD

**Issue by khaledelbasha22** [creativetimofficial/material-tailwind#198]
**after upgrade from 0.3.4 to 1.2.3** 

tabs not support the form input  because it's destroy all content with inputs and render other one 

are you  have any way to solved  it ??

**Comment by sajadevo** [comment]
Hi @khaledelbasha22,

The issue is fixed on v1.2.4 please update to the latest version for resolving this issue.

Cheers,
Sajad
