### ISSUE TITLE
Material Tailwind React components difficult to customise

### ISSUE THREAD

**Issue by bymi15** [creativetimofficial/material-tailwind#200]
The components are very difficult to customise in general.
For example, for the Select component: https://www.material-tailwind.com/docs/react/select
If we try to make it a smaller width: 
```
<Select
    size="md"
    variant="static"
    className="w-24"
>
```
From inspecting the rendered elements, there seems to be an outer `div` component with className: `min-w-[200px]` that cannot be overridden or targeted via `className`

**Comment by sajadevo** [comment]
Hi @bymi15,

The `min-w-[200px]` is the minimum with for the select and the entire with of the `Select` component is related to it's parent element please do the following and you'll see that the width of the `Select` component is working fine.

```jsx
<div className="w-96">
  <Select
    size="md"
    variant="static"
  >
</div>
```

As you can see the width of `Select` component is related to it's parent as much width you set for it's parent element it will be applied to the `Select` component as well.

Cheers,
Sajad
