### ISSUE TITLE
React: Updating a controlled select value causes selected value to disappear

### ISSUE THREAD

**Issue by pyskywalker** [creativetimofficial/material-tailwind#202]
I made a controlled select value and once i update it , it momentarily appears on the input then disappears.### This is my code
`
import React, {
  useEffect,
  useState,
  useRef,
  createRef,
  useImperativeHandle,
  forwardRef,
} from "react";
import { Option, Select } from "@material-tailwind/react";
import { TAILWIND_COLORS } from "../utils/constants";
import { useField } from "formik";

const SelectField = (props, ref) => {
  const [field, meta, helpers] = useField(props);
  const [value, setValue] = useState(props.value);
  const select = useRef();

  useImperativeHandle(ref, () => ({
    setValue: (value, shouldValidate = true) => setValue(value),
    getInput: () => value,
  }));

  const handleChange = (value) => {
    if (value !== props.value) {
      setValue(value);
      props.onChange && props.onChange(props.name, value);
    }
  };

  return (
    <div className="mb-8 relative">
      <Select
        variant="static"
        size="lg"
        label={props.label}
        // onBlur={props.onBlur}
        onChange={(value) => handleChange(value)}
        error={meta.touched && meta.error}
        color={TAILWIND_COLORS.primary}
        value={value}
      >
        {/* <Option value="">Select {props.label}</Option> */}
        {props.options.map((item, index) => (
          <Option value={item.value} key={index}>
            {item.label}
          </Option>
        ))}
      </Select>

      {meta.touched && meta.error ? (
        <span className="text-xs text-red-400 shadow-sm absolute -bottom-5 left-3">
          {meta.error}
        </span>
      ) : null}
    </div>
  );
};

export default forwardRef(SelectField);

`

https://user-images.githubusercontent.com/79524205/186226566-c24c18ab-b71e-405d-a773-0f5c2eb01aac.mp4

**Comment by sajadevo** [comment]
Hi @pyskywalker,

Please take a look to the [Select Props](https://www.material-tailwind.com/docs/react/props/select) to know how they're working.

Cheers,
Sajad

**Comment by pyskywalker** [comment]
Hi @sajadevo ,
Do you maybe have an example i can work with, the explanation was very vague
Thanks

**Comment by sajadevo** [comment]
> Hi @sajadevo , Do you maybe have an example i can work with, the documentation explanation was very vague Thanks

Here is an example of controlled select component.

```jsx
import { useState } from "react";
import { Select, Option } from "@material-tailwind/react";

export default function Example() {
  const [selectValue, setSelectValue] = useState(null);

  return (
    <div className="w-72">
      <Select
        label="Select Version"
        value={selectValue}
        onChange={(value) => setSelectValue(value)}
      >
        <Option value="react">React</Option>
        <Option value="vue">Vue</Option>
      </Select>
    </div>
  );
}
```

Cheers,
Sajad

**Comment by megancallenbach** [comment]
I have the same issue.... The value just dissappears
