### ISSUE TITLE
Accordion closing when modal opens

### ISSUE THREAD

**Issue by Vitalsine85** [creativetimofficial/material-tailwind#204]
I have a button inside of my accordion that opens a modal. When the modal opens, it closes the accordion. When I exit the modal, the accordion reopens. I'd like the accordion to stay open the entire time, only opening and closing when the accordion header is clicked by the user. What's the best way to go about that? 

Thanks!

**Comment by sajadevo** [comment]
Hi @Vitalsine85,

You can use the state as the Accordion is a controlled component you can control the open and close state for it using the `useState` hook, you just need to keep the `open` value `true` even when opening the modal.

Cheers,
Sajad
