### ISSUE TITLE
Accordion with multiple accordions inside

### ISSUE THREAD

**Issue by Ewasuu** [creativetimofficial/material-tailwind#205]
I'm trying to put some accordions inside another accordion, but the last accordion inside is being cut by the parent accordion, any idea?

Thanks!!

**Comment by sajadevo** [comment]
Hi @Ewasuu,

Any image from the issue that you can provide for me?

Cheers,
Sajad

**Comment by jim-pickering** [comment]
![image](https://user-images.githubusercontent.com/4935614/188519476-ac80b9e9-8dde-4cec-8d53-2b5543d54b80.png)

**Comment by treyholt** [comment]
Any update on this?

**Comment by sajadevo** [comment]
Hi guys,

I've listed it for fixing on the next update of the library.

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey @Ewasuu, @jim-pickering and @treyholt,

This issue has been fixed. Update to v1.2.5 

Cheers,
Sajad
