### ISSUE TITLE
Tooltip only shows when child component is a Button. 

### ISSUE THREAD

**Issue by williamlmao** [creativetimofficial/material-tailwind#207]
Works
```
<Tooltip content="Material Tailwind">
      <Button variant="gradient">Show Tooltip</Button>
    </Tooltip>
```

Does not work
```
<Tooltip content="Material Tailwind">
     <div>hi</div>
 </Tooltip>
```

**Comment by sajadevo** [comment]
Hi @williamlmao,

The tooltip only works with components that passes a ref you can not use it with a simple div because no ref is passed for it, please add a ref for the div and the same for the tooltip so to make it working.

Cheers,
Sajad
