### ISSUE TITLE
Unable to change the fill color of the react radio component

### ISSUE THREAD

**Issue by rabidcodemonkey** [creativetimofficial/material-tailwind#208]
Unable to set the fill color for the radio component to a custom tailwind color using the react version of the library.  Unable to determine the proper custom theme settings.

I added a custom color to the tailwind.configs.js file:

```
  theme: {
    extend: {
      colors: {
        body: '#eceff1',
        primary: '#f96302', //- Customer Orange
      },
    },
  },
```

I am able to use this color when styling a Material Tailwind React Button

```js
export const customTheme = {
  button: {
    defaultProps: {
      className: 'bg-primary text-white',
    },
  },
```

![image](https://user-images.githubusercontent.com/29692095/190901487-15c66074-c103-475f-bbb2-aad28e73e502.png)

However, I have not been able to figure out the correct way to custom style the Material Tailwind React Button.

I have tried setting my own color

```
  radio: {
    defaultProps: {
      color: 'primary',
    },
    styles: {
      colors: {
        primary: {
          color: 'text-primary',
          border: 'checked:border-primary',
          before: 'checked:before:bg-primary',
        },
      },
    },
  },
```

I have tried setting it through styles:

```
  radio: {
    // defaultProps: {
    //   className: `text-primary checked:text-primary
    //      fill-primary checked:fill-primary
    //      accent-primary checked:accent-primary`,
    // },
    styles: {
      base: {
        input: {
          borderColor: 'border-primary',
        },
      },
    },
  },
```

![image](https://user-images.githubusercontent.com/29692095/190901252-d13d0411-2d26-41e7-b604-1d0339e8f64a.png)

I've tried setting it through tailwind:

```css
@layer base {
  input[type='checkbox'],
  input[type='radio'] {
    &:checked {
      @apply text-white accent-primary;
    }
  }
}
```

What am I missing?

**Comment by sajadevo** [comment]
Hi @rabidcodemonkey,

Could you please make your issue more descriptive?

Cheers,
Sajad

**Comment by rabidcodemonkey** [comment]
My apologies.  I've updated the description.

**Comment by sajadevo** [comment]
Hi @rabidcodemonkey,

Please use the following for adding new color for the radio button component.

```js
styles: {
 colors: {
  primary: {
     color: "text-primary",
     border: "checked:border-primary",
     before: "checked:before:bg-primary",
   },
 }
}
```

Cheers,
Sajad
