### ISSUE TITLE
how override minimum input width

### ISSUE THREAD

**Issue by hesxenon** [creativetimofficial/material-tailwind#214]
I have a few components that are actually a lot smaller than the default minimum width of inputs (200px iirc). How can I stop `@material-tailwind` from setting this minimum width?

**Comment by sajadevo** [comment]
Hi @hesxenon,

Please use the following method:
1. Create a theme object for input:
```js
const theme = {
  input: {
    styles: {
      base: {
        container: {
          minWidth: "min-w-[100px]",
        }
      }
    }
  }
}
```

2. Then pass the `theme` as a value for the `value` prop in `<ThemeProvider value={theme} />`.

Cheers,
Sajad
