### ISSUE TITLE
First Tooltip Child in a PopoverContent default showed

### ISSUE THREAD

**Issue by tannerboysun** [creativetimofficial/material-tailwind#219]
For some reason, the first child with a tooltip in a popover will default be displayed and will not go away until MouseEnter and MouseLeave.

Upon dismissing the popover and opening it again, the tooltip is displayed again by default. 

Using Tooltip on a list of buttons in a popover content block.

![image](https://user-images.githubusercontent.com/13684634/189051811-e2a6e66b-5d69-439d-851a-77e9f50f452e.png)
![image](https://user-images.githubusercontent.com/13684634/189052539-1d2355c6-6da1-4022-a78a-4a17b12436a3.png)

**Comment by sajadevo** [comment]
Hi @tannerboysun,

Please read the documentation for tooltip for those sort of cases: [Tooltip](https://www.material-tailwind.com/docs/react/props/tooltip).

Cheers,
Sajad

**Comment by sajadevo** [comment]
@tannerboysun,

I've tested this issue and it seems it's a bug with the package we're using for positioning the elements like Popover and Tooltip, I'll try to fix it ASAP.

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey @tannerboysun,

I test this issue and it's not really an issue or bug it's the default behaviour since the first element is get auto focus and shows the tooltip, if you use a `div` or `span` it won't do that.

Cheers,
Sajad
