### ISSUE TITLE
Select component gets auto-focused when it has a default value

### ISSUE THREAD

**Issue by EilifAkerjordet** [creativetimofficial/material-tailwind#220]
I use Formik to control the value of all my form components. If I have an initialValue for the select component, when refreshing my screen, the select components value is first blank for a sec, then it gets set, and the input is focused.

Could this be because its value is set in a useEffect internally?

**Comment by sajadevo** [comment]
Hi @EilifAkerjordet,

Could your please share a video from this issue so that I can know what's happening.

Cheers,
Sajad

**Comment by EilifAkerjordet** [comment]
Upgrading to latest verion fixed it ! @sajadevo. I was at 1.0.2:)
