### ISSUE TITLE
is there a typescript example available?

### ISSUE THREAD

**Issue by divramod** [creativetimofficial/material-tailwind#221]
hey, 

i created a react typescript app with create-react-app.
i am trying to convert the example from here: https://www.creative-tim.com/product/material-tailwind-dashboard-react
to typescript but having no real success.

is there somewhere a typescript example for the react dashboard?

thx for providing the dashboard!

**Comment by sajadevo** [comment]
Hi @divramod,

This dashboard was built on top of the first version of Material Tailwind one year ago but we'll update it to the latest version ASAP.

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey @divramod,

I've updated the dashboard to the latest version of @material-tailwind/react, you can give it a try.

Cheers,
Sajad
