### ISSUE TITLE
Customization of Chip coponent

### ISSUE THREAD

**Issue by Kilian-mescam** [creativetimofficial/material-tailwind#222]
Hello,

I id like to customize the Chip component in order to use my own colors, etc. I use react and typescript.
I receive an error due to my customization "TypeError: Cannot convert undefined or null to object"

I, firstly, created a customChip component based on Chip component from Material-tailwind :

`interface CustomChipProps extends Omit<ChipProps, "color"> {
    variant?: "filled" | "gradient";
    className?: string;
    value: string;
    color?:
    | "primary"
    | "secondary"
    | "warning"
}`

`export default function CustomChip(props: CustomChipProps) {
    return <Chip {...(props as any)} />;
}`

then I create a baseChip component based on my CustomChip component : 

`export const BaseChip: React.FC<React.PropsWithChildren<CustomChipProps>> = (
    props: React.PropsWithChildren<CustomChipProps>
): JSX.Element => (
    <CustomChip
        variant={props.variant}
        color={props.color}
        value={props.value}
    />
);
`

on my theme file, i added the chip component, I think the problem is here, my I did an error but i don't know how to custom each part : 

`
    chip: {
        defaultProps: {
            variant: 'filled',
            color: 'primary',
            show: true,
            size: 'sm',
        },
        valid: {
            variants: ['filled'],
            colors: ['primary', 'secondary', 'warning', 'dark'],
        },
        styles: {
            base: {
                position: "relative",
            },
            variants: {
                filled: {
                    primary: {
                        background: 'bg-primary',
                        color: 'text-white',
                    },
                    secondary: {
                        background: 'bg-secondary',
                        color: 'text-dark',
                    },
                },
            },
            closeButtonColor: {
                filled: {
                    primary: {
                        color: 'text-white',
                    },
                    secondary: {
                        color: 'text-dark',
                    },
                    warning: {
                        color: 'text-white',
                    },
                },
            },
        },
`

Thank you
Kilian`

**Comment by sajadevo** [comment]
Hi @Kilian-mescam,

Please use this page and see the theme object structure for the chip component. [Chip Theme](https://www.material-tailwind.com/docs/react/theme/chip)

Cheers,
Sajad

**Comment by Kilian-mescam** [comment]
Hi Sajad,

it seems that we can't add new colors in chip customization. It works well for me but when I add new colors inside "valid" i got the error  "TypeError: can't convert undefined to object"

**Comment by sajadevo** [comment]
Hi @Kilian-mescam,

Please see this link and it's related files the variants is an object of objects of each color name: [https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/theme/components/chip/chipFilled.ts](https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/theme/components/chip/chipFilled.ts)

Cheers,
Sajad

**Comment by Kilian-mescam** [comment]
Hi @sajadevo 

Thank you, I didn't see all these informations. It helps a lot. 
In my opinion you shoultd put it on the website in order to help more.

Kilian

**Comment by Kilian-mescam** [comment]
Hi,

ok thank you, but I don't really understand what do I have to put as
"Object" ? Is it written somewhere ? How can I know ?
thank you
