### ISSUE TITLE
Dialog animation is very slow in chrome

### ISSUE THREAD

**Issue by nont65** [creativetimofficial/material-tailwind#223]
I tried dialog demo in chrome, it's very slow (but in edge, firefox is smooth). Can you see this problem?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/565772/190835737-f2d7e824-be48-442b-a194-0b66b8a21271.gif)

**Comment by sajadevo** [comment]
Hi @nont65,

It's not a slow animation it's lagging could you please tell me which version of chrome you're using because it's working very smooth on my machine.

Cheers,
Sajad

**Comment by nont65** [comment]
My chrome version is 105.0.5195.102.

**Comment by jetuala** [comment]
I had the same problem last week, but for some reason, it's working smoothly now. I just updated my Chrome version to 105.0.5195.127

**Comment by sajadevo** [comment]
Hey guys,

The Dialog components should be outside the other components not nested inside card or other components in the page.

Cheers,
Sajad

**Comment by AnotherFurakam** [comment]
I solved it by activating hardware acceleration.

**Comment by joshortner** [comment]
@sajadevo Dialog components shouldn't be nested? Is there a reason for this or docs explaining? This seems like a major limitation, though I could be missing something.

**Comment by cirogg** [comment]
Having this issue on Chrome. Mozilla working fine. It is not about nesting anything.

**Comment by damsfx** [comment]
The issue seems to be related to Chrome implementation of `showModal()`.   

See : 
 - https://issues.chromium.org/issues/40252064
 - https://issues.chromium.org/issues/40893232
