### ISSUE TITLE
Progress not visible when percentage too low

### ISSUE THREAD

**Issue by slhck** [creativetimofficial/material-tailwind#227]
It seems the label of the progress is rendered within the actual progress bar.

With 0 percentage, I do not even see the label:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/582444/191013400-2bab8bcc-359f-423a-be33-29b80774883f.png">

Setting to percentage 5 and rendering the label "Unknown":

<img width="876" alt="image" src="https://user-images.githubusercontent.com/582444/191013312-7f2521ef-2221-4a74-b4f4-bd23150898e7.png">

When the percentage is high enough, the text can be read:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/582444/191013223-60d9446d-32e2-47f0-8650-658857586766.png">

It would be better if the label was rendered above the bar, so that it can still be read even when the percentage is low.

**Edit:** Alternatively, the text color could be inverted so that it becomes readable.

**Comment by sajadevo** [comment]
Hey @slhck,

This issue has been fixed. Update to v1.2.5 

Cheers,
Sajad
