### ISSUE TITLE
Select Component should behave like other Inputs

### ISSUE THREAD

**Issue by tannerboysun** [creativetimofficial/material-tailwind#229]
The Select component in the React library does not behave as an input should and as the other inputs in Material Tailwind. If you set the value of the Select component as a state, if you don't change the state you shouldn't be able to change the select.

For example:

```
const [selection, setSelection] = useState("cat");

<Select label="Select Option" value={selection}>
<Option value="cat">Cats</Option>
<Option value="dog">Dogs</Option>
<Option value="mice">Mice</Option>
<Option value="chicken">Chicken</Option>
<Option value="sloth">Sloth</Option>
</Select>
```

This should keep the selection component on the Cats option, because I have not implemented an onChange method. 
However the Selection component in Material Tailwind allows me to change the selection to something else although the state is Cats. 

This is not normal behavior for selection components. All the other Material Tailwind inputs behave properly and not the selection component.

**Comment by Shotto-P** [comment]
You are right. I faced this problem as well yesterday. It was created as a button, not an input element.

**Comment by sajadevo** [comment]
Hey @tannerboysun and @Shotto-P 

This issue has been fixed. Update to v1.2.5 

Cheers,
Sajad
