### ISSUE TITLE
TypeError: Cannot destructure property 'open' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by oztek22** [creativetimofficial/material-tailwind#230]
Hi,

I am having the following error while implementing the Select component.
 

<img width="909" alt="image" src="https://user-images.githubusercontent.com/14314089/192108809-574ff68c-47eb-44f9-bd9b-a0dc9545b1ec.png">

Here is the minimum code to reproduce the error.

```
import { Option, Select } from '@material-tailwind/react';
import { Fragment } from 'react';

export default () => {
  console.log('rendering hsn modal');
  const hsnData = JSON.parse('{"6505":{"description":"sax","uqc":"PAC"},"7013":{"description":"asas","uqc":"PAC"},"56041000":{"description":"sdd","uqc":"PAC"},"73239990":{"description":"","uqc":"PAC"}}');
  const QuantityCodes = {
    BAG: 'BAGS',
    BDL: 'BUNDLES',
    BOU: 'BILLION OF UNITS',
    BOX: 'BOX',
    BTL: 'BOTTLES'
  };

  return <>
    {Object.keys(hsnData).map(hsnId => <Fragment key={hsnId}>
      <h4 className="text-sm md:text-base font-semibold text-dark">HSN ID : {hsnId}</h4>
      <div className="mb-4 md:mb-7">
        <div className="mt-2">
          <label className="text-dark text-sm md:text-base mb-2 block">Unique Quantity Code</label>
          <Select className="form-select appearance-none p-3 block w-full m-0" label='Unique Quantity Code' color='green' value={hsnData[hsnId].uqc} onChange={(e) => { hsnData[hsnId].uqc = e; }}>
            {Object.keys(QuantityCodes).map(code => <Option value={code} key={code}>{code}-{QuantityCodes[code]}</Option>)}
          </Select>
        </div>
      </div>
    </Fragment>)}
  </>
};
```

Also, everything works on my local setup but on production it fails. I'm using `parcel build` for the production environment.

**Comment by VlodkoMr** [comment]
The same issue in my production build :(

**Comment by sajadevo** [comment]
Hey guys,

I've tested the library and this issue doesn't happening even based on @oztek22 example code provided, probably there is a version issue or something with library setup please do the following for fixing this issue:
1. Update to the latest version of @material-tailwind/react.
2. Follow the guide on [how to install and setup @material-tailwind/react](https://www.material-tailwind.com/docs/react/installation)

Cheers,
Sajad
