### ISSUE TITLE
Tab Animation Suggestion

### ISSUE THREAD

**Issue by flamz3d** [creativetimofficial/material-tailwind#231]
Nice work, looks and behaves very nicely, thank you for your work. One suggestion would be to add the ability to control (or remove altogether) the animation of the Tab selector. I currently cannot use it because it is too slow.

**Comment by sajadevo** [comment]
Hey @flamz3d,

Thanks for using our library, for sure you can make it off please do the following.

```jsx
<TabsBody animate={{
 mount: { transition: { duration: 0, times: 0 } },
 unmount: { transition: { duration: 0, times: 0 }}
}}>
...
</TabsBody>
```

Cheers,
Sajad

**Comment by ToyWalrus** [comment]
@sajadevo Can this be documented somewhere? Right now the `animation` type looks like this
```ts
type animation = {
  mount?: object,
  unmount?: object,
}
```
which is extremely unhelpful and does not take advantage of the use of Typescript. Just a suggestion, since I had to search for a while to find this. Thanks!

**Comment by sajadevo** [comment]
@ToyWalrus,

I'm working on the project to improve it more 2023 will have more of better improvements and updates, I'll mark this one also as one of the updates that should be done.

Cheers,
Sajad
