### ISSUE TITLE
withMT not revering to used node_module folder within MonoRepo packages folder

### ISSUE THREAD

**Issue by valoricDe** [creativetimofficial/material-tailwind#232]
Hey there, I'm developing an electron app and came across an issue.

If using withMT in a monorepo packages folder it might not reach the node_module with 

```
content: [
    "./node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
  ],
```
because the node_modules are residing in an level above the package.
<img width="1161" alt="Bildschirmfoto 2022-09-26 um 17 05 08" src="https://user-images.githubusercontent.com/22564188/192312504-749ce07a-5e76-4885-bdc1-f2a89bdbb927.png">

Not sure if this is something which should be amended. Just wanted to bring to awareness. cheers

**Comment by amykhar** [comment]
I just came to report the same issue.  I'm trying to use this as part of a component library in my monorepo, and everything ends up white.

**Comment by valoricDe** [comment]
@amykhar a workaround is to include it yourself:
```
const withMT = require('@material-tailwind/react/utils/withMT')

module.exports = withMT({
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    '../../node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}',
    '../../node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
})

```

**Comment by sajadevo** [comment]
Hey @valoricDe and @amykhar,

I've added a section related to tailwind config for @material-tailwind/react in monorepos this will help people who're using the library with a monorepo, I can't add any specific path for monorepos because it will be different on different projects.

Here are the links:
1. Next.js: [https://www.material-tailwind.com/docs/react/guide/next#with-monorepo](https://www.material-tailwind.com/docs/react/guide/next#with-monorepo)
2. CRA: [https://www.material-tailwind.com/docs/react/guide/cra#with-monorepo](https://www.material-tailwind.com/docs/react/guide/cra#with-monorepo)
3. Remix: [https://www.material-tailwind.com/docs/react/guide/remix#with-monorepo](https://www.material-tailwind.com/docs/react/guide/remix#with-monorepo)
4. Vite: [https://www.material-tailwind.com/docs/react/guide/vite#with-monorepo](https://www.material-tailwind.com/docs/react/guide/vite#with-monorepo)

Cheers,
Sajad

**Comment by Mihai-github** [comment]
Hello, @sajadevo 

    I'm having some issues integrating this library with Remix ... for some kind of reason is not working and I've followed the docs.
   At the moment I'm getting this:
  
react_devtools_backend.js:2655 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 

and 


overrideMethod @ react_devtools_backend.js:2655
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useContext2 @ react.development.js:1602
useTheme @ theme.js:1
(anonymous) @ index.js:1
renderWithHooks @ react-dom.development.js:14977
updateForwardRef @ react-dom.development.js:17036
beginWork @ react-dom.development.js:19090
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23956
performUnitOfWork @ react-dom.development.js:22768
workLoopSync @ react-dom.development.js:22699
renderRootSync @ react-dom.development.js:22662
performSyncWorkOnRoot @ react-dom.development.js:22285
scheduleUpdateOnFiber @ react-dom.development.js:21873
updateContainer @ react-dom.development.js:25474
(anonymous) @ react-dom.development.js:26013
unbatchedUpdates @ react-dom.development.js:22423
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26012
hydrate @ react-dom.development.js:26078
hydrateApp @ entry.client.tsx:10
requestIdleCallback (async)
(anonymous) @ entry.client.tsx:20
react.development.js:1618 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at useContext2 (react.development.js:1618:21)
    at useTheme (theme.js:1:2230)
    at index.js:1:2315
    at renderWithHooks (react-dom.development.js:14977:18)
    at updateForwardRef (react-dom.development.js:17036:20)
    at beginWork (react-dom.development.js:19090:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23956:7)

Maybe this helps with debugging.

**Comment by sajadevo** [comment]
Hey @Mihai-github,

Can I've your code? I need to reproduce that.

Cheers,
Sajad
