### ISSUE TITLE
'Option' is not exported from '@material-tailwind/react'.

### ISSUE THREAD

**Issue by Hat52** [creativetimofficial/material-tailwind#243]
When trying to export Option it gives the error saying 'Option' is not exported from '@material-tailwind/react'.
If you think this Issue should be worked upon then I would like to  create a PR.
![image](https://user-images.githubusercontent.com/44437268/194758978-9db166a7-b6e5-4589-90a4-7f298574cc0f.png)

**Comment by luisFebro** [comment]
This is the same error that prevent me to use the latest version of this lib

**Comment by sajadevo** [comment]
Hey guys,

I've tested the latest version of the library and this issue is not true for it, please update to v1.2.4 to get the latest updates.

Cheers,
Sajad
