### ISSUE TITLE
" Vue.js versions are coming soon"  does not give any indication

### ISSUE THREAD

**Issue by tvld** [creativetimofficial/material-tailwind#248]
We are about to start a new greenfield project. Loving your framework, it really would help if there is at least some kind of indication about the support of Vue.js. Weeks?  Month? Year?

**Comment by sajadevo** [comment]
Hey @tvld,

Thanks for your supports, unfortunately the Vue.js version release is not clear because we didn't start to work on it, probably it will happen in 2023.

Regards,
Sajad

**Comment by cn-2k** [comment]
This would be great.

**Comment by aliromero** [comment]
We are eagerly anticipating support for Vue 3!

**Comment by mkraha** [comment]
Any update regarding vue 3 ?

**Comment by cn-2k** [comment]
I would be happy to help if this project starts
