### ISSUE TITLE
Dialog z index 

### ISSUE THREAD

**Issue by RussHide** [creativetimofficial/material-tailwind#249]
How can i change  z-index, i have Select component inside Dialog component, and options disapear

I tried style={{zIndex: 999999}} un Dialog, and DialogBody and it didn't work
![Screenshot_1](https://user-images.githubusercontent.com/63980905/196073447-ef10af2d-3241-4351-8d1d-d89a3d197561.png)
![Screenshot_2](https://user-images.githubusercontent.com/63980905/196073452-d1ea9aed-3ef3-4fed-93c6-b27dc3d295e9.png)

**Comment by sajadevo** [comment]
Hi @RussHide,

Thanks for using our product, it's not related to `z-index` it's the overflow issue, please add the following for `<Dialog />` and `<DialogBody />`:

```className="overflow-auto"```

Cheers,
Sajad

**Comment by sajadevo** [comment]
Hey @RussHide,

This issue has been fixed.

Cheers,
Sajad
