### ISSUE TITLE
ThemeProvider stopped working when upgrading from 1.0.3 -> 1.2.4

### ISSUE THREAD

**Issue by EilifAkerjordet** [creativetimofficial/material-tailwind#255]
What the title says. Surely I have to be missing some kind of API change here? I had a custom theme I was using with the ThemeProvider in 1.0.3, when upgrading to 1.2.4 it just stopped working. When logging out:
```
const theme = useTheme()
console.log(theme)
```
It appears like none of my custom styles are set... My theme looks like this:
```
const defaults = {
  select: {
    styles: {
      base: {
        container: {
          className: '!min-w-min',
        },
        select: {
          className: '!text-white',
        },
      },
    },
  },
  radio: {
    styles: {
      base: {
        label: {
          className: '!text-white',
        },
      },
    },
  },
  textarea: {
    styles: {
      base: {
        textarea: {
          className: '!text-white !placeholder:text-black',
        },
        label: {
          className: '!text-grey-400',
        },
      },
    },
  },
  input: {
    styles: {
      base: {
        container: {
          className: '!min-w-min',
        },
        input: {
          className: '!placeholder-grey-400 !text-white',
        },
      },
    },
  },
}
```

**Comment by sajadevo** [comment]
Hey @EilifAkerjordet,

Could you please share your repo with me or give me access?

Cheers,
Sajad

**Comment by EilifAkerjordet** [comment]
@sajadevo after hours of ripping out what little hair I have left trying to solve this, I realized the issue. Im in a monorepo, and had forgotten to update one of the packages to 1.2.4. Once I did everything works like a charm!
