### ISSUE TITLE
Removing properties from the screens object does not effect

### ISSUE THREAD

**Issue by shamssujon** [creativetimofficial/material-tailwind#257]
I was trying to customize the screens for my project. I can add a new screen or edit any existing one, but if I remove any of the predefined properties from the object, it does not remove them from the code. 

This is my tailwind.config.js . 
![Screenshot_2](https://user-images.githubusercontent.com/9370979/204078566-fed84d96-edbe-4138-8cf4-f72836a300b1.png)

You see I have edited the screen values and it works as expected. Now let's say I want my screen up to the **lg** breakpoint, so I want to remove **xl** and **2xl** from the object. But removing "xl" and "2xl" does not actually remove them from the code. Instead, they stay with their default value (xl: "1140px", "2xl": "1320px",)

Is it a bug or I am doing any wrong here? Any idea how to fix it?

**Comment by sajadevo** [comment]
Hey @shamssujon,

The screen values are coming as default value by material tailwind theme provider and the only way that you can remove them is to set the xl: "" and 2xl: "" to empty strings.

Cheers,
Sajad
