### ISSUE TITLE
address tag causes an error when used within Typography in NextJS

### ISSUE THREAD

**Issue by amykhar** [creativetimofficial/material-tailwind#261]
Using an address tag within a Typography component in NextJS causes the following error:

> Unhandled Runtime Error
> 
> Error: Hydration failed because the initial UI does not match what was rendered on the server.

```
import {
    Typography,
} from "@material-tailwind/react";

const AddressPage = () => {
    return (
        <Typography variant="medium whitespace-pre-line" className="normal-case">
            <address>The Address Page</address>
        </Typography>
    );
}

export default AddressPage;

```

Without the Typography wrapper, there is no issue with ```<address>```

**Comment by sajadevo** [comment]
Hey @amykhar,

It's not an issue with the library, basically you can't use `<address />` tag inside the typography tags in html like `h1, h2, h3, p` and so on, if you even use the `<address />` inside the `<p />` tag it will show you the exact same error.

Here is a quick fix for this issue:
```
import {
    Typography,
} from "@material-tailwind/react";

const AddressPage = () => {
    return (
        <Typography as="div" variant="medium whitespace-pre-line" className="normal-case">
            <address>The Address Page</address>
        </Typography>
    );
}

export default AddressPage;
```

**Comment by amykhar** [comment]
Thank you :). Sorry for the bogus bug report.
