### ISSUE TITLE
Dialog for React

### ISSUE THREAD

**Issue by danthmn** [creativetimofficial/material-tailwind#262]
Hi, when you click on the 'open dialog' button, a new style attribute appears in the body tag. This causes the navbar to shift minimally.
`style="overflow: hidden; padding-right: 17px;"`

![image](https://user-images.githubusercontent.com/111145442/205932814-dec3c435-8656-4320-84c1-9bc00f11d92b.png)

But the same does not happen in the normal material tailwind html variant.
Is this behavior intentional? If so, how can i get around this problem?

Bests,
Dan

**Comment by sajadevo** [comment]
Hey @danthmn,

Could you please share a small video of this with me I can't get you correctly.

Cheers,
Sajad

**Comment by danthmn** [comment]
Hi @sajadevo ,

I provided a link to the video (only 10MB files are allowed to upload here).
The behavior is same if you install the package locally.

https://my.hidrive.com/share/jwoue4c25f

Bests,
Dan

**Comment by sajadevo** [comment]
@danthmn,

It's not an issue, when the dialog is opened the scrollbar disappeared and the entire make a bit of more with because of the scrollbar space.

Cheers,
Sajad

**Comment by danthmn** [comment]
@sajadevo 

Why is this behavior not present in the "HTML" version of MTW? I just found this behavior  in the react component.

Best,
Dan

**Comment by sajadevo** [comment]
@danthmn,

The react version is more stable than html version and these small issues will be fixed on html version as well.

Cheers,
Sajad
