### ISSUE TITLE
Accordion dropdown to only icon not entire header

### ISSUE THREAD

**Issue by Randyhall91** [creativetimofficial/material-tailwind#266]
Hello I was working with the Accordion and I'd like to put other actionable Icons in the header bar but since the entire header has the onClick and It doesn't seem like I can get to the drop down button to just have it control the setOpen. If this possible I would appreciate the info.

**Comment by sajadevo** [comment]
Hey @Randyhall91,

You need to have the `onClick` on the content of the `Accordion` as following:

```
<AccordionHeader>
  <span onClick={() => handleOpen(1)}>What is Material Tailwind?</span>
</AccordionHeader>
```

Cheers,
Sajad
