### ISSUE TITLE
How to use theming ficture to properly create a dark/light theme switcher

### ISSUE THREAD

**Issue by Dakauann** [creativetimofficial/material-tailwind#272]
Hello, currently the documentation is a bit too confusing(kinda empty) about how to use the theming ficture of the librarie, can someone explain what are the propertys i need to pass on the theme vaue object? thx.

**Comment by sajadevo** [comment]
Hey @Dakauann,

On the end of each component page there is a theme and props definition links that you can use to know about each component theme structure and props definition here is an example of the [Button](https://www.material-tailwind.com/docs/react/button#theme) component.

Cheers,
Sajad

**Comment by Dakauann** [comment]
> Hey @Dakauann,
> 
> On the end of each component page there is a theme and props definition links that you can use to know about each component theme structure and props definition here is an example of the [Button](https://www.material-tailwind.com/docs/react/button#theme) component.
> 
> Cheers, Sajad

Hello, thx for your response, btw, there's not much information about a global theming, primary, secondary and default colors, how could I set those to be in all the components?

**Comment by sajadevo** [comment]
@Dakauann there is no primary or secondary colors it's uses only the following colors on this page [https://www.material-tailwind.com/docs/react/colors](https://www.material-tailwind.com/docs/react/colors) and you can modify those colors using the tailwindcss config

Cheers,
Sajad
