### ISSUE TITLE
how to customize the label of checkbox component ?

### ISSUE THREAD

**Issue by Ebinsha** [creativetimofficial/material-tailwind#273]

**Comment by sajadevo** [comment]
Hey @Ebinsha,

There is a `labelProps` that you can use for modifying the checkbox label here is an example:

```
<Checkbox labelProps={{ className: "font-bold" }} />
```

Cheers,
Sajad

**Comment by Ebinsha** [comment]
Thank you!

**Comment by sajadevo** [comment]
@Ebinsha you can use the `!` modifier before the classnames to mark your classnames as important.
