### ISSUE TITLE
Customizing color palette (HTML version of material-tailwind)

### ISSUE THREAD

**Issue by Sicaa** [creativetimofficial/material-tailwind#275]
Hi!
Thank you for this cool library :)
I'm trying this out and the documentation is not very clear about how we can customize color palette for the HTML version of this lib. I would like to achieve this from my `tailwind.config.js` file. Can you give me some example?

**Comment by sajadevo** [comment]
Hey @Sicaa,

You can do it simply as tailwindcss colors customisation.

```
colors: {
 "blue-gray": {
   500: "#ffffaa"
  }
}
```

Cheers,
Sajad
