### ISSUE TITLE
Getting the selected radio button

### ISSUE THREAD

**Issue by habibifa** [creativetimofficial/material-tailwind#276]
So maybe I'm just not smart enough to figure this out. But I can't seem to get the selected radio button. Is there a way to do this?
Example
I have a quiz which has 4 answer options and the user can choose one of the radio buttons. Now as the user clicks the check Answer button I am not able to get the selected radio button so that I can check.
Could someone please help me?

**Comment by sajadevo** [comment]
Hey @habibifa,

Here is the example that you can use:

```
import React from "react";
import { Radio } from "@material-tailwind/react";

export default function Example() {
  const [value, setValue] = React.useState("");
  console.log(value);
  return (
    <div className="flex gap-10">
      <Radio
        id="html"
        value="html"
        name="type"
        label="HTML"
        onChange={(e) => setValue(e.target.value)}
      />
      <Radio
        id="react"
        value="react"
        name="type"
        label="React"
        onChange={(e) => setValue(e.target.value)}
      />
    </div>
  );
}
```

Cheers,
Sajad
