### ISSUE TITLE
Why are nonce, onResize, onResizeCapture required for some component?

### ISSUE THREAD

**Issue by luckymaniac** [creativetimofficial/material-tailwind#277]
I am using "react": "^18.2.0", typescript, "@material-tailwind/react": "^1.2.5" and "tailwindcss": "^3.2.1".

For most of components, e.g. Button, requires none, onResize, onResizeCapture at least "undefined", unless there is type error on compiling

Here's my sample code.

```
import { Button } from '@material-tailwind/react'

<Button nonce={undefined} onResize={undefined} onResizeCapture={undefined}>
   Save
</Button>
```

Did I miss something on configuration?

**Comment by Mwi-Mat** [comment]
I am experiencing this same issue after upgrading from 1.2.4 to 1.2.5 and can't seem to resolve it. Is their a known solution for this currently? Or updated config setting?

**Comment by ical10** [comment]
I have to strictly set to `"1.2.4"` to avoid this.

**Comment by andreasawires** [comment]
same issue here, even using the 1.2.4 version. I'm using NextJS 12 and tailwind 3.2.1

**Comment by EilifAkerjordet** [comment]
@andreasawires, i am fine on v1.2.4. I would check your lockfile to make sure what version(s) you have installed. I had some trouble there!

**Comment by sajadevo** [comment]
Hey everyone,

I was super busy with the html version of the project, I'll fix this issue on the next update ASAP.

Cheers,
Sajad

**Comment by rakshit087** [comment]
Any update on this? Let me know would love to contribute.

**Comment by sajadevo** [comment]
@rakshit087 this month I'll release an update with all the fixes.

**Comment by sajadevo** [comment]
@ical10 @luckymaniac @Mwi-Mat @EilifAkerjordet @andreasawires @rakshit087 guys I want to reproduce this issue but can't do that could anyone share some small reproduced version of this issue?

Cheers,
Sajad

**Comment by hamen** [comment]
I'm facing the same issue. I have created a simple Next.js project and followed the doc: `npm i @material-tailwind/react`.

Many components show this error:
![image](https://user-images.githubusercontent.com/19003/218865160-d20d8f7f-badc-44b2-8791-6088f911175b.png)

I can dev like this, but `npm run build` is yelling at me when it's time to deploy 😓

As reference, 
![image](https://user-images.githubusercontent.com/19003/218865510-642dcd26-04ac-4503-8f0b-0ac0a7c20f55.png)

Thanks @sajadevo

**Comment by rakshit087** [comment]
As of now, either install version 1.2.4 or you can also fill the required
props (nonce, onResize, etc) and keep them undefined.

**Comment by hamen** [comment]
Hi @rakshit087, I can surely fill the required props, even if it gets very noisy quickly. When I do, I get errors on the client side, about non-existent properties like onResize.

**Comment by pppp606** [comment]
It seems to be a problem caused by the version of `@types/react`. They are addressing the same issue with mui.

https://github.com/mui/material-ui/issues/35287

**Comment by sajadevo** [comment]
This issue only happens if you use React 17 to fix it please update to React 18 this will fix the issue it't not an issue with the library it's an issue with the React it self. but still if you want to use React 17 with the library do the following:

1. Create a new `index.d.ts` file in the root of your project.
2. Then put the following code into that file.

```
declare global {
  namespace React {
    interface DOMAttributes<T> {
      onResize?: ReactEventHandler<T> | undefined;
      onResizeCapture?: ReactEventHandler<T> | undefined;
      nonce?: string | undefined;
    }
  }
}
```

**Comment by hamen** [comment]
Thank you for the directions. I updated Next and React:

![image](https://user-images.githubusercontent.com/19003/219147772-10211c0c-ea2c-410e-a5a3-834cca372a1e.png)

but I'm still seeing this:
![image](https://user-images.githubusercontent.com/19003/219147944-ef5bd322-45f9-4cd2-af50-debe781e279a.png)

What really did the trick was installing the `types`:
```
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
```

No more errors, and now I have such a nice button! 😍
![image](https://user-images.githubusercontent.com/19003/219152316-c3c4e582-adc9-4b21-8018-43c8c35466a6.png)
