### ISSUE TITLE
accodionbody doesnt change his heigth

### ISSUE THREAD

**Issue by rominabocon** [creativetimofficial/material-tailwind#283]
Im working with react and tailwind, i have this dependency "@material-tailwind/react": "^1.2.4",
But cant change the height of the Accordion Body, is set by style inline on 119px no matter how much text do you have in the tab.
Any solution?

**Comment by sajadevo** [comment]
Hey @rominabocon,

I've fixed this issue on `^1.2.5` please update to the latest version.

Cheers,
Sajad
