### ISSUE TITLE
Hii! I've been using material-tailwind for a while now, I'm liking it, but I encountered a problem when using radio buttons, they can't do multiple selections.

### ISSUE THREAD

**Issue by a-s-t-e-y-a** [creativetimofficial/material-tailwind#287]
I m using Radio button for my project and i want them to be multiple select and but by default they are not multiple select and their is no option to make them

**Comment by sajadevo** [comment]
@a-s-t-e-y-a the radio buttons are used to select only one option for multiple selection you need to use `<Checkbox />`.

Cheers,
Sajad
