### ISSUE TITLE
React: Input Outline, disable shrink when empty or placeholder

### ISSUE THREAD

**Issue by UltimatumGamer** [creativetimofficial/material-tailwind#290]
Hey, is there a way to disable ***shrink*** in an outlined input field?
So i can use a label and a placeholder at the same time.
```jsx
  <Input
    variant="outlined"
    label="label"
    labelProps={{ shrink: false }} // ?
    containerProps={{ shrink: false }} // ?
    placeholder="placeholder"
  />
```
![image](https://user-images.githubusercontent.com/46068693/216829473-d39e443a-26d5-4b3f-87ec-64297c4ba483.png)
![kqVnhi4ewN](https://user-images.githubusercontent.com/46068693/216829685-9fc5f082-4f86-47bb-803d-4bb447623e09.gif)
Expected: 
![image](https://user-images.githubusercontent.com/46068693/216829491-cb65a0bb-f6f9-4f87-a351-ff6c68f29aa1.png)

It could work like this example from *mui* https://mui.com/material-ui/react-text-field/#shrink

**Comment by sajadevo** [comment]
Hey @UltimatumGamer 

This feature has been added please update to v1.4.0. and you will be able to add the `shrink={true}` on the input component.

Cheers,
Sajad
