### ISSUE TITLE
Missing properties from Components

### ISSUE THREAD

**Issue by egalindoEH** [creativetimofficial/material-tailwind#297]
I've upgraded from v1.2.3 to the latest version (1.4.2) and some problems occurred.

For example, using Button, Popover, Accordion, AccordionHeader, TextArea, etc.

![image](https://user-images.githubusercontent.com/108294256/219175146-16f337f6-81c7-4099-a992-1401f7bafa11.png)

![image](https://user-images.githubusercontent.com/108294256/219174851-66143af4-4f13-49b6-8314-2d438d4d6625.png)

Example code with error:
`<Textarea
    rows={3}
    {...register("comments", { required: false})}
     className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
/>`

even if I add the example code from documentation shows me the same error:
`<Textarea size="md" label="Textarea Medium" />`

I'm using react v18.2.0

Thanks.

**Comment by sajadevo** [comment]
Hey there please refer to this issue #277
