### ISSUE TITLE
How to remove the text input border's on focus for the react version ?

### ISSUE THREAD

**Issue by dopey2** [creativetimofficial/material-tailwind#300]
Hello,

I want to remove the border of an input when the input gets focused for the react version.
I've tried to set the following rules "**!border-b-0 !focus:border-b-0**" but it is not working.

The code:

```jsx
<Input              
        className="!border-b-0 !focus:border-b-0 "
        variant="standard" 
        placeholder="Static"
        label=""
/>
```
The result:

![tw-input](https://user-images.githubusercontent.com/22329040/221416355-234425a3-2b6e-4f5e-9d86-5a294f4897cf.png)

Thanks in advance  and great lib by the way !

**Comment by sajadevo** [comment]
Hey there,

You can do that using the `labelProps` for the input:

```jsx
<Input              
    variant="standard" 
    placeholder="Static"
    label=""
    labelProps={{ className: "before:border-0 peer-focus:border-transparent" }}
/>
```

Cheers,
Sajad

**Comment by dopey2** [comment]
I tried your version, and i still got the bottom border

**Comment by sajadevo** [comment]
@dopey2 this would work

```jsx
<Input
  variant="standard"
  placeholder="Static"
  label=""
  className="focus:border-blue-gray-200"
  labelProps={{
    className: "peer-focus:after:scale-x-0",
  }}
/>
```
