### ISSUE TITLE
Typescript Problems

### ISSUE THREAD

**Issue by tannerboysun** [creativetimofficial/material-tailwind#304]
Hello I am using the react library and just updated material tailwind, now all of my inputs and buttons have typescript problems with missing attributes. 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/13684634/224366520-a4e48891-4445-44d1-904b-fb9eeb2c40e2.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/13684634/224366661-0c12e66c-e868-40c0-bc7e-a4528e26aee4.png">

Adding them like this resolves it but this really gets messy:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/13684634/224366820-4e165688-cc6f-4ebe-a5ca-0d7c5d538dd4.png">

Version in package.json:  "^1.2.3"

**Comment by sajadevo** [comment]
Hey @tannerboysun,

It's not with the library it's an issue with react please check #277 issue.

Cheers,
Sajad
