### ISSUE TITLE
'Input With Button' Example

### ISSUE THREAD

**Issue by mdmvgithub** [creativetimofficial/material-tailwind#309]
In your example labeled 'Input With Button' , at https://www.material-tailwind.com/docs/react/input ,
when an email is introduced and the button is pressed, the size of the surrounding div is reduced and the button gets out of the border.

It's an interesting example, if you solve , it will very nice

Tested with chrome and firefox

![Pantallazo](https://user-images.githubusercontent.com/34844419/227011787-8e69f365-40e3-49d6-8fcc-f3800e2a2816.png)

**Comment by sajadevo** [comment]
Hey @mdmvgithub,

Thanks for reporting that, I've just fixed that issue you can check the docs and get the fixed version of this example.

Cheers,
Sajad
