### ISSUE TITLE
[Help Needed] Select component does not return an event.

### ISSUE THREAD

**Issue by 35C4n0r** [creativetimofficial/material-tailwind#310]
```
<Select name={"country"} onChange={handleInputChange} label={"Select Country"}>
    <Option>meow1</Option>
    <Option>meow2</Option>
    <Option>meow3</Option>
</Select>
``` 

```
function handleInputChange(event){
    console.log(event);
    console.log(event.target);
}
```

onChange is Triggered but logging the event i see that event is Empty and target is undefined.
on replacing `<Select>` and `<Option>` with normal `<select>` and `<option>` the code works alright.

**Comment by 35C4n0r** [comment]
@sajadevo can you please take a look at this :)

**Comment by sajadevo** [comment]
@35C4n0r it's because that the `onChange` for our custom select component returns the selected value not any event.

Regards,
Sajad

**Comment by AshutoshDash1999** [comment]
@sajadevo can you show a code example?

**Comment by AshutoshDash1999** [comment]
> @sajadevo can you show a code example?

Got it.

```
<Select
            label="Select Your Role"
            onChange={(e) => setUserData({ ...userData, role: e })}
            name="role"
            value={userData?.role}
          >
            <Option value="buyer">Buyer</Option>
            <Option value="seller">Selller</Option>
          </Select>
```

**Comment by rezzakali** [comment]
> Collaborator
But, If I need event instead of value, like to get formData directly like server action in react(form)
