### ISSUE TITLE
Improve framer motion library bundle size

### ISSUE THREAD

**Issue by mobinyardim** [creativetimofficial/material-tailwind#315]
Hi,

I recently used your repository for my last project and enjoyed it, especially the animations. but there is a problem that bothers me the framer motion bundle size in the first load js is about 300kb. after some googling I found [this page](https://www.framer.com/motion/guide-reduce-bundle-size/#how-to-reduce-the-size-of-the-motion-component) in framer motion documentation. with this approach, the first js size will significantly decrease. I can help you with PR by the way if you are ok with it I can change them.
![Screenshot from 2023-04-05 14-02-12](https://user-images.githubusercontent.com/31635962/230056473-de421a61-5fea-4d07-b9ae-8797c8dc3dc6.png)

**Comment by sajadevo** [comment]
Hey @mobinyardim,

Thanks for your help, absolutely you can contribute and open a PR I really appreciate it, that will help me to make the library more stable.

Regards,
Sajad
