### ISSUE TITLE
Override classes on components

### ISSUE THREAD

**Issue by rmanalan** [creativetimofficial/material-tailwind#32]
Since this is using Tailwind, we should be able to override classes on components. For example, I'd love to change the bg color of a popover, but I can't. Will this be supported?

**Comment by sajadevo** [comment]
Hey @rmanalan 
Thanks a lot for the feedback we will have something better to control the design of the components the way you want on the next upcoming version.

**All the best**
**Sajad**

**Comment by rmanalan** [comment]
Thanks @sajadevo. Any idea when this feature will be available? I'm trying to determine if I should create a custom fork for my needs or just wait for this feature. My immediate need is to be able to change the color of a popover. I was thinking that it would be nice to just allow for passing down the `className` prop to the material-ui components so that the classes on the components can be overridden.

**Comment by sajadevo** [comment]
Hello @rmanalan don't worry I will make a new update and add the className prop for the components until we make a better way for doing that, the new update will be available in one or two days.

**All the best**
**Sajad**

**Comment by sajadevo** [comment]
Hello @rmanalan now you can update the material tailwind to the latest version and use the className props for the components.

**All the best**
**Sajad**
