### ISSUE TITLE
Question: How long until Angular?

### ISSUE THREAD

**Issue by harvanchik** [creativetimofficial/material-tailwind#33]
I'm looking for good TailwindCSS Components for Angular.  Roughly how long until this will be available for Angular?

**Comment by sajadevo** [comment]
Hey @harvanchik 
Until now we are in the testing stage of our framework and collecting feedbacks to make the material-tailwind better and easy to use, and once we publish the stable react version of Material Tailwind v1.0.0 then we will work on the angular version.

We will inform you once we publish the angular version of Material Tailwind.
Feel free to ask any type of question related to Material Tailwind we appreciate it and answer to is as soon as possible.

**All the best**
**Sajad**

**Comment by cnbebop** [comment]
Any updates?
