### ISSUE TITLE
Module not found "@heroicons/react/24/outline"

### ISSUE THREAD

**Issue by ComputerKeeda** [creativetimofficial/material-tailwind#330]
I am experiencing an issue while using Material Tailwind's Alert component in my Next.js project. Upon running my application, I encounter the following error message:

**Module not found: Can't resolve '@heroicons/react/24/outline'**

This error seems to be related to an import that the Alert component is making to '@heroicons/react/24/outline', which cannot be resolved.

Here are the steps to reproduce the issue:

1. Install Material Tailwind package in your Next.js project:

       npm install @material-tailwind/react@latest

i encounter this error on `"@material-tailwind/react": "^2.0.0",` version

2. Import the Alert component in one of your pages:

       import { Alert } from '@material-tailwind/react';

I believe this error is caused by a missing dependency in Material Tailwind's Alert component. Specifically, the component is trying to import the '@heroicons/react/24/outline' module, which is not included in the package's dependencies.

To fix this issue, I suggest adding '@heroicons/react' as a peer dependency in the Material Tailwind package.json file. This will ensure that the package can only be installed if '@heroicons/react' is also installed, and will prevent this error from occurring.

**Comment by ComputerKeeda** [comment]
although we can  install '@heroicons/react' as a separate dependency in our Next.js project, which should also resolve the issue.

🙂

**Comment by mobinyardim** [comment]
same issue

**Comment by angvzrz** [comment]
I have same issue when just wrapping the app inside the ThemeProvider component

**Comment by sajadevo** [comment]
Hey there,

I've released a patch update the `v2.0.1` and this will fix your issue.

Cheers,
Sajad

**Comment by mauro-sousa** [comment]
Use this command:
npm install @heroicons/react
