### ISSUE TITLE
Carousel Not Working for Vite React Typescript and Multiple Type Errors to Other Components (An upgrade from v1.2.4 to v2.0.0)

### ISSUE THREAD

**Issue by Mattttyyyy** [creativetimofficial/material-tailwind#332]
Hello I got this message: 

Type '{ children: Element[]; className: string; }' is missing the following properties from type 'Pick<CarouselProps, "children" | "color" | "transition" | "translate" | "slot" | "style" | "title" | "loop" | "onClick" | "className" | "navigation" | "key" | "defaultChecked" | ... 252 more ... | "slideRef">': nonce, onResize, onResizeCapturets(2739)
(alias) const Carousel: React.ForwardRefExoticComponent<Pick<CarouselProps, "children" | "color" | "transition" | "translate" | "slot" | "style" | "title" | "loop" | "onClick" | "className" | "navigation" | "key" | ... 253 more ... | "slideRef"> & React.RefAttributes<...>>
import Carousel

The implementation I did was simply copy and paste from the documentation... according to some investigations:

"The problem might be related to the type definition of the Carousel component in the @material-tailwind/react library. If using TypeScript and the type definition is incorrect, it might cause a compilation error."
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/171e23b6-6552-4b06-b83c-1765b1c2bb43)

Button has this type error too but it renders no problem, with Carousel, the screen turns white and does not render.

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/12218ba6-4dc0-4a13-9b95-853d313460ab)

This is the doc I followed for version 2.0.0
https://www.material-tailwind.com/docs/react/carousel

Lastly, Other components seems to show type errors ever since I installed the latest version 2.0.0 from v1.2.4
they are as follows:
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/f3ab61cb-216f-4dbf-9b26-e254fe863a1c)

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/a081f61e-5a2c-412c-8e87-600ec8fce749)
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/95bb0551-a688-40d0-9a76-f7636b2d302e)
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/b18a3503-d5fd-4f0e-8100-fc0d585f5a96)
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/ac4ca872-32f8-42ca-9bb2-f80ffe11511f)

Thank you~~!

**Comment by Mattttyyyy** [comment]
Tried these suggestions but still the same thing happened ~
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/2c7339c9-3452-4f95-bf83-7fda9638a27a)

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/e96dc4bc-c01d-4e3e-8751-d85e3d523262)

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/15c5c135-a305-4635-ab6d-9fa35dae5dee)

**Comment by Mattttyyyy** [comment]
It seems there is no problem if you install it fresh on v2.0.0 but these errors would occur if one will upgrade from v1.2.4 to v2.0.0 

Carousel worked as well when I did this:
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/7f5f5265-fdb0-409a-9d26-3b3b1394763f)

But still has type errors.
For now I'd rollback to v1.2.4 my project and just keep this record here as concern. I love this MT so I'd like it being smooth in integrating to real world projects so I'll help as much as I can 

Thanksss~~

**Comment by sajadevo** [comment]
Hey there,

I've released a patch update the `v2.0.1` and this will fix your issue.

Cheers,
Sajad
