### ISSUE TITLE
Does the documentation needs an update since the boilerplate needs an additional dependency installed? 

### ISSUE THREAD

**Issue by Mattttyyyy** [creativetimofficial/material-tailwind#333]
It seems like a little update is needed for the instructions of the documentation in installation using Vite? I'm just worried for the beginners...  

The documentation here only mentioned installing MT but when I ran it, it required @heroicons/react dependency in which I did, so I feel like we should include this on the installation instructions right? 

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/eb616077-e43b-452a-8486-e93950676c83)
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/4ffe3113-ab1e-4647-b414-b52f61cbcdfa)
![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/1b567cb5-6219-40a5-aa47-d8421e864c39)

![image](https://github.com/creativetimofficial/material-tailwind/assets/93179600/d8b84f4a-c049-45de-939a-6082e664c918)

**Comment by mobinyardim** [comment]
Hello,

I wanted to inform you that the bug you encountered has been resolved in version 2.0.1. You can find more information about the fix in this [issue](https://github.com/creativetimofficial/material-tailwind/issues/330#issuecomment-1549350319)

**Comment by Mattttyyyy** [comment]
Got it, thank you~
