### ISSUE TITLE
Custom styles for theme provider not working

### ISSUE THREAD

**Issue by zasuh** [creativetimofficial/material-tailwind#335]
I'm creating my own custom styles (no shadow and no border radius), but they seem to not be working when implemented like so:

```
const theme = {
  navbar: {
    styles: {
      base: {
        initial: {
          borderRadius: 0
        },
      },
    },
  },
};
```

**Comment by sajadevo** [comment]
Hey there,

The theme structure you've used in note correct, please use the link below for the theme object type guide.
[https://www.material-tailwind.com/docs/react/theme/navbar](https://www.material-tailwind.com/docs/react/theme/navbar)

Regards,
Sajad

**Comment by Darren120** [comment]
> Hey there,
> 
> The theme structure you've used in note correct, please use the link below for the theme object type guide. https://www.material-tailwind.com/docs/react/theme/navbar
> 
> Regards, Sajad

what type is object??
