### ISSUE TITLE
Broken Style on nextjs 13

### ISSUE THREAD

**Issue by Reyuki-san** [creativetimofficial/material-tailwind#337]
I've tried to follow the guide to [install material-tailwind in nextjs](https://github.com/creativetimofficial/material-tailwind/issues/258), but when I try it using the [sidebar component](https://www.material-tailwind.com/docs/react/sidebar), it doesn't seem to work correctly, is there something I'm missing?

![image](https://github.com/creativetimofficial/material-tailwind/assets/126035476/72c8b9d6-643a-4c11-b6c9-4a5bc8a4bed1)

I've tried removing node_modules, reinstalling dependencies, and deleting the .next folder but it doesn't seem to be working

**Comment by mobinyardim** [comment]
did you wrap your tailwind confg with withMT() function ? and did you add 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
``` 
to your globals.css file?

**Comment by Reyuki-san** [comment]
thanks for your response!
i've already added it, here's the [source code](https://github.com/Reyuki-san/bilibili-dl/blob/dev/apps/web/app/global.css)

**Comment by mobinyardim** [comment]
@Reyuki-san, I have reviewed the source code, but regrettably, I am unable to run it to test any potential workarounds. Nonetheless, I am still willing to assist if you need it.

**Comment by Reyuki-san** [comment]
I tried to reproduce the code on [stackblitz](https://stackblitz.com/github/Reyuki-san/bilibili-dl) but it doesn't seem to work, it somehow throws an error ```jsh: command not found: next```. I'm confused and don't know what to do, are you able to help me by giving me a hint? thanks!

**Comment by Darren120** [comment]
> did you wrap your tailwind confg with withMT() function ? and did you add
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> to your globals.css file?

hello, with MT works but if I toggle dark and light it doesn't follow anymore

**Comment by Reyuki-san** [comment]
closed, now i use pages insetead of app dir, and switch to mantine

**Comment by Darren120** [comment]
> closed, now i use pages insetead of app dir, and switch to mantine

then ur doing CSR. If you want SSR, Mantine uses styled comps, which will have flash of unstyled comp issue.
