### ISSUE TITLE
Drawer is broken in v2.0.2

### ISSUE THREAD

**Issue by rustyro** [creativetimofficial/material-tailwind#361]
CSS attributes on both the `background blur div` and `drawer div` do not update properly when open=true
- Transition on the drawer div is not set to none, 
- although the background blur div gets rendered, opacity remains 0

**Comment by toitzi** [comment]
+1 Having the same issue

**Comment by sajadevo** [comment]
Hey there,

Please update to v2.0.3 for fixing this issue.

Regards,
Sajad

**Comment by rhenaldkarrel** [comment]
> Hey there,
> 
> Please update to v2.0.3 for fixing this issue.
> 
> Regards, Sajad

Hello, I have used v2.0.3 but still got the issue. The backdrop opacity is 0, and it has translate x -300px on the inline style that can't be overridden (unless with `!important`). And I don't know why, this issue also happened on the Modal and Select/Option components.
