### ISSUE TITLE
 Issue with Label of Input Component

### ISSUE THREAD

**Issue by AkshatK805** [creativetimofficial/material-tailwind#362]
Label is overflowing the textbox on change of window size.

![image](https://github.com/creativetimofficial/material-tailwind/assets/107099693/22640cb7-04b1-4797-ae36-259fb2c3664f)
![image](https://github.com/creativetimofficial/material-tailwind/assets/107099693/2903b82d-85ef-4db8-ab6e-9cafc29faaad)

The code for the input is simply this
<Input
      label="Find answers to most common questions"
  />

Can anyone help me with this issue?

**Comment by sajadevo** [comment]
Hey there,

Please update to v2.0.3 for fixing this issue.

Regards,
Sajad
