### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by yamiteru** [creativetimofficial/material-tailwind#37]
## Expected Behavior
Should be able to use in TS project without any errors saying it `Could not find a declaration file for module `@material-tailwind/react/*`.

## Current Behavior
I cannot use it in TS project as seen here:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/34185465/119355905-16520880-bca6-11eb-8350-3f6e342597fc.png">

## Possible Solution
Add native TS support or create typings.

## Steps to Reproduce (for bugs)
1. Create empty NextJS/React app with TS support
2. Install material-tailwind
3. Import material component

## Your Environment
Current version of material-tailwind. NextJS TS project.

**Comment by sajadevo** [comment]
Hello @the-yamiteru,
Unfortunately we don't have any support for typescript, but we will add it soon.

**All the best**
**Sajad**

**Comment by rmanalan** [comment]
Just wondering if there's a plan to add TS support soon?

**Comment by remidosol** [comment]
@rmanalan I'm wondering too, I really need it for my bootcamp homeworks for React.

**Comment by remidosol** [comment]
@rmanalan I'm wondering too, I really need it for React homeworks that are in a bootcamp.

**Comment by dohomi** [comment]
@sajadevo is there any progress to follow up on? I'd be interested in it too

**Comment by worapolburaphan** [comment]
anything I can skip this error os ts support?

**Comment by KvngAlka** [comment]
> anything I can skip this error os ts support?

You can name you file <filename>.js
eg. if the filename is index.tsx, you can make it index.js.
it will still work in the project

**Comment by aviemet** [comment]
For those looking to use this library before typescript is fully supported, you can create your own declaration file and type the components as you use them. It adds a bit of legwork, but if your editor provides feedback, defining the types should be pretty simple.

Create a file called `decs.d.ts` at the same location as your `tsconfig.json` file, or if you prefer it to be located eslewhere, make sure that path is in the `compilerOptions: { path: {} }` object. Here's an example of how I've begun typing this library, so far only three components:

```
declare module '@material-tailwind/react/Icon' {
	const Icon: React.FC<{ name: string, size?: string, color?: string }>
	export default Icon
}
declare module '@material-tailwind/react/H1' {
	const H1: React.FC<{ color: string }>
	export default H1
}

declare module '@material-tailwind/react/H6' {
	const H6: React.FC<{ color: string }>
	export default H6
}

```

**Comment by yamiteru** [comment]
@aviemet Thanks. 

It's actually a lot of leg work and I don't understand why the author doesn't rewrite it into TS. There are even apps and small utilities that help with JS->TS migration.

**Comment by aviemet** [comment]
After looking at the issue history and last update, I'm beginning to think this project has been abandoned by the author.

**Comment by mattienodj** [comment]
Thanks for the hint @aviemet! I'm using this in a Storybook, Tailwind, TS, React set up and have started a Gist that I'll keep updated as I go.

https://gist.github.com/mattienodj/6293b565c60cc26f2d6ca0480f06acfa

**Comment by sajadevo** [comment]
**Hi everyone**

After a long break update for Material Tailwind now we come with totally new plans 2022 will be the year that Material Tailwind v1.0.0 is going to be released with TypeScript support and all new components and features.

**All the best**
**Sajad**

**Comment by sajadevo** [comment]
**Hi everyone**

To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).
Material Tailwind updates will be posted their as well!

**All the best,
Sajad**

**Comment by AndreCox** [comment]
### Fix to get typescript working
Hi everyone I have a solution to use this in a type script project! You won't have type checking but it will definitely work until we get version 1.0.0
 I saw someone recommended to declare each component individually. This works well however it is quite time consuming to add for each component. Instead you can use `declare module "@material-tailwind/react/*";`  This will add support for all components and I have had no issues so far.

**Comment by JonathanAGonzalez** [comment]
Hello, I have this problem in my project, here is a picture of the warning. Sniff
![image](https://github.com/creativetimofficial/material-tailwind/assets/57570825/4450d993-e45f-483a-af50-5c2ba6b0ec42)

**Comment by AndreCox** [comment]
> Hello, I have this problem in my project, here is a picture of the warning. Sniff ![image](https://user-images.githubusercontent.com/57570825/255999049-4450d993-e45f-483a-af50-5c2ba6b0ec42.png)

This is a issue with version 2.0.7 See a simple fix here in this issue while it is being fixed https://github.com/creativetimofficial/material-tailwind/issues/405#issuecomment-1648681352
