### ISSUE TITLE
Question: Can I use @material-tailwind for a serious project

### ISSUE THREAD

**Issue by shareef99** [creativetimofficial/material-tailwind#38]
I just wanna ask that stable release of material-tailwind is not released yet so
Can I use @material-tailwind for a serious project? 

I am using NextJS with TypeScript and Material-UI but Material-UI is not working properly with the tailwindcss.

**Comment by sajadevo** [comment]
Hello @shareef99,

You can use material tailwind with any type of projects you want but currently we don't have any support for typescript.

**All the best**
**Sajad**

**Comment by shareef99** [comment]
Thanks, I will use it and eagerly waiting for typescript support.
