### ISSUE TITLE
Slider thumb offset bug

### ISSUE THREAD

**Issue by AndreCox** [creativetimofficial/material-tailwind#386]
Hello noticed this slight issue with the slider component.

I create a simple nextjs page like this

```ts
import { Slider } from '@material-tailwind/react'

const Test = () => {
  return (
    <div className="w-96">
      <h1>Test</h1>
      <Slider className="" />
    </div>
  )
}

export default Test
```

![image](https://github.com/creativetimofficial/material-tailwind/assets/25626962/c70c459f-908a-4501-9612-e545a89233e1)
This creates a page like this with the slider thumb slightly offset to the top.

I have tested this on different browsers and removed all css except for tailwind.

Hopefully this can be resolved.

Thanks :)

**Comment by sajadevo** [comment]
Hey there,

I can't reproduced that issue, could you please help provide me a link or repo?

Regards,
Sajad

**Comment by AndreCox** [comment]
I am also unable to reproduce the issue, in a blank project.

**Comment by AndreCox** [comment]
Also for anyone with the same issue, I tailwindcss and material tailwind to the latest versions. Then deleted all of my node modules then reinstalled everything and that fixed the issue.
