### ISSUE TITLE
Dark Mode is not working

### ISSUE THREAD

**Issue by abhishekmardiya** [creativetimofficial/material-tailwind#400]
Dark mode is  not working after warapping tailwind css configurations with the withMT() function.

**Comment by armandleopold** [comment]
I am curious, how do you enable dark mode ?

**Comment by abhishekmardiya** [comment]
> I am curious, how do you enable dark mode ?

documentation dark mode:https://tailwindcss.com/docs/dark-mode

**Comment by armandleopold** [comment]
yes ok but it's not implemented for material-tailwind components https://github.com/creativetimofficial/material-tailwind/issues/319#issuecomment-1519537781

**Comment by sajadevo** [comment]
This will implement in the v3, currently working on that. as we already have an issue related to that I'm closing that one.

**Comment by aliwarraich007** [comment]
Hi, tailwind dark mode classes dont work after using the withMT() function?
Did anyone find a workaround?

**Comment by henchoznoe** [comment]
I have the same problem... :(
