### ISSUE TITLE
Tabs OnChange not passed/firing?

### ISSUE THREAD

**Issue by RobertjanTuit** [creativetimofficial/material-tailwind#401]
Hi,

I was wondering if the Tabs component onChange event should be firing or if I'm doing something wrong? I'm doing a basic: 
`<Tabs onChange{(e)=>console.log(e)}`
And not seeing anything in the console. 

In the mean-time I'm adding an onClick to the TabHeader which seems to work? But I think that will not cover all scenario's (keyboard etc..)

I don't see it mentioned in the materia-tailwind docs, but I do see it in the material docs?

cheers,
_rj

**Comment by sajadevo** [comment]
@RobertjanTuit the `onChange` is not an event or prop for the Tabs.

**Comment by moeinrahimi** [comment]
so how to know when tabs are changed?
