### ISSUE TITLE
Release 2.0.7

### ISSUE THREAD

**Issue by alexanderteno** [creativetimofficial/material-tailwind#404]
I don't know if it's just me, but by coincidence I was running `yarn update` or `upgrade` or whichever and grabbed `2.0.7`.

It seems like the bundle doesn't include the `index.js` and `index.d.ts` which was making my `vite` runner to fail to build.

# `2.0.7` 🔴 
![image](https://github.com/creativetimofficial/material-tailwind/assets/5354921/0c5d98bd-45fc-4612-bf01-344697755a78)

# `2.0.6` 🟢 

![image](https://github.com/creativetimofficial/material-tailwind/assets/5354921/e94763a9-058e-47e8-942a-c910a9d47d16)

# `2.0.5` 🟢 

![image](https://github.com/creativetimofficial/material-tailwind/assets/5354921/7bf57d22-4a86-4a56-89fb-20dbe63b961b)

**Comment by tdanh2k** [comment]
Running into the same problem.

**Comment by daengsoe** [comment]
Me too..

**Comment by kenzaflow** [comment]
here too

**Comment by david-marstree** [comment]
Yes, me too.

**Comment by lonebots** [comment]
I am having the same issue 😞

**Comment by jsonggan** [comment]
Same here

**Comment by pierratono** [comment]
Same issue here 😞

**Comment by rezzakali** [comment]
same issue here

**Comment by kenzaflow** [comment]
@sajadevo please see this

**Comment by sajadevo** [comment]
Hey guys,

This issue is fixed on `v2.0.8`
