### ISSUE TITLE
2.0.7 doesnt work, 2.0.6 does.

### ISSUE THREAD

**Issue by ebootdpr** [creativetimofficial/material-tailwind#405]
error message, (I dont have time to fully track the problem)
![image](https://github.com/creativetimofficial/material-tailwind/assets/36868128/5abb6f4c-ac96-45fd-87b1-fb86e9a9d924)
packages.json(BEFORE) NOT WORKING
![image](https://github.com/creativetimofficial/material-tailwind/assets/36868128/efbc6fe7-4d6d-4f90-9e99-27eaf871c044)
packages.json(AFTER) **WORKING**
![image](https://github.com/creativetimofficial/material-tailwind/assets/36868128/af1c67bb-a656-4319-b140-c1834e6f83f9)

**Comment by Hiich** [comment]
I've got the same issue, upgrading the app broke my nextjs app (with typescript)

**Comment by Migarl** [comment]
It seems the raw source code was published and not the compiled one.

**Comment by Inmoresentum** [comment]
Same issue here :(

**Comment by DaviSpeck** [comment]
Same here :(

**Comment by leanhquoc1710** [comment]
Same issue and I must downgrade 2.0.6

**Comment by killy10o10** [comment]
same issue here

**Comment by YidirK** [comment]
i have the same issue , but jsute when I build my app (ps: I use **Vite**).I spent two days looking for where the problem comes from. I think it's better to stay on the 2.0.6 for the moment.

**Comment by harshal255** [comment]
exactly, I have been getting the same error in the 2.0.7 version

**Comment by AndreCox** [comment]
Yeah same issue using nextjs

**Comment by AndreCox** [comment]
If anyone needs a quick fix just set the package version to 2.0.6 in your package.json for the time being.

**Comment by denislutz** [comment]
Same here, thanks a lot for your work, but pls establish some basic CI to prevent something like that.

**Comment by sajadevo** [comment]
Hey guys,

This issue is fixed on `v2.0.8`
