### ISSUE TITLE
Cannot find module '@material-tailwind/react/utils/withMT'

### ISSUE THREAD

**Issue by Rdrudra1999** [creativetimofficial/material-tailwind#406]
[Cannot find module '@material-tailwind/react/utils/withMT'](https://stackoverflow.com/questions/76742330/cannot-find-module-material-tailwind-react-utils-withmt)

**Comment by lnfernandobr** [comment]
I try to integrate material-tailwind with Meteor 2.12 and I'm getting the same error

```
Error: Cannot find module '@material-tailwind/react/utils/withMT'
```
If i try to replace  `'@material-tailwind/react/utils/withMT'` to `'@material-tailwind/react/src/utils/withMT'` then I get a new error

``` 
no such file or directory, scandir 'PATH/material-tailwind/node_modules/@material-tailwind/react/components/'
```

**Comment by muhamad-rizki** [comment]
it looks like on v2.0.7 is broken, v2.0.6 works fine

**Comment by lnfernandobr** [comment]
For me, the only version that worked well was the `1.4.2`
