### ISSUE TITLE
Module not found: Can't resolve '@material-tailwind/react'

### ISSUE THREAD

**Issue by lkmSasanga** [creativetimofficial/material-tailwind#408]
I have installed the package already but getting module not found. I'm using Nextjs 13.4.11

**Comment by abouhir** [comment]
the same problem with me but with react project

**Comment by Rdrudra1999** [comment]
Downgrade to "@material-tailwind/react": "^2.0.5", , it will solve your problem

**Comment by ComputerKeeda** [comment]
@Rdrudra1999 you answer was correct bro but it was still showing the same error in my device so I tried this code

`"@material-tailwind/react": "2.0.5",`

and it worked 
thanks bro 😃

**Comment by sethumadh** [comment]
Hi, The issue is still there.  I am using react vite , and none of the versions are working atm.

**Comment by mahatoHariom** [comment]
> @Rdrudra1999 you answer was correct bro but it was still showing the same error in my device so I tried this code
> 
> `"@material-tailwind/react": "2.0.5",`
> 
> and it worked thanks bro 😃

IT worked and  "@material-tailwind/react": "2.0.6",` too  we just have to remove ^ from our version

**Comment by mahatoHariom** [comment]
when will the material tailwind support react server component out of the box

**Comment by rohit-ojha-10** [comment]
Downgrading to 2.0.5 worked , thank you so much!!!!

**Comment by rtmann** [comment]
Still broken, confirmed downgrading works.

**Comment by sajadevo** [comment]
Hey guys,

This issue is fixed on `v2.0.8`.

**Comment by ComputerKeeda** [comment]
> I'm at v2.1.9 and this problem exists for me.

try downgrading to version `v2.0.8`
