### ISSUE TITLE
Issue with the nextjs server component

### ISSUE THREAD

**Issue by mahatoHariom** [creativetimofficial/material-tailwind#411]
When does it will support server component out of box

**Comment by aliemami-coder** [comment]
Hi,
you can wrap the Material Tailwind component in other components and add `use client` to the first line of the file.

example:
create a file with `MTCustom.tsx` (or jsx) and use this code:

``` javascript
"use client";
 
import { ThemeProvider, Button } from "@material-tailwind/react";
 
export { ThemeProvider, Button };
```

use Button or ThemeProvider in other files:

```` javascript
import "/styles/globals.css";
 
import { ThemeProvider } from "./path/to/MTCustom";
 
export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}
````

[https://www.material-tailwind.com/docs/react/guide/next](https://www.material-tailwind.com/docs/react/guide/next)
