### ISSUE TITLE
`<Select />` dynamic `<Option />` bug

### ISSUE THREAD

**Issue by kenzaflow** [creativetimofficial/material-tailwind#419]
The `<Select />` component: you can't change the `<Option />` dynamically because when you do and select an item and update the value, it doesn't show as selected until after 2-3 clicks, so there is something wrong.

https://github.com/creativetimofficial/material-tailwind/assets/74398451/cb37563c-10b0-4882-95fd-3472c8bca425

```tsx

const [data, setData] = useState<{ categoryId: string | undefined }>({ categoryId: undefined })

const [search, setSearch] = useState('')

const categories = useMemo(() => {
  if (categoriesRaw && search !== '') {
    const fuse = new Fuse(categoriesRaw, {
    keys: ['name', 'slug', 'id'],
    threshold: 1,
    })
    const result = fuse.search(search)
    return result.map((result) => result.item)
  }
  if (categoriesRaw) return categoriesRaw
  return []
}, [categoriesRaw, search])


...

{!categoriesError && (
  <>
    <Select
      color='deep-orange'
      onChange={(newValue) => {
      if (typeof newValue === 'string') {
      setData({ categoryId: newValue })
      }
      }}
      value={data.categoryId}
      disabled={categoriesLoading}
      className='text-black'
      label='Categoría'>
        <Option value=''>{categoriesLoading ? 'Cargando...' : 'Ninguna'}</Option>
    
      {...categories.map((category, index) => {
        return (
          <Option
            key={index + category.id + category.name + category.slug}
            value={String(category.id)}
            disabled={false}>
              {category.name}
          </Option>
        )
      })}
    </Select>
  </>
)}
```

**Comment by ddimalen-uoa** [comment]
I am having the same issue

**Comment by tannerboysun** [comment]
We have the same issue in our app too and some of our dynamic selects work and others don't. It's so bad we have contemplated building our own select component that looks identical for now.

**Comment by kenzaflow** [comment]
If I remove this

```tsx
<Option value=''>{categoriesLoading ? 'Cargando...' : 'Ninguna'}</Option>
```

And only leave the .map, and setting the `value={VALUE || undefined}` when there is not a value works, but well, that disables me the possibility of being able to put an option to select like "empty".

That would not be a problem if an "X" to reset could be added to it

**Comment by ddimalen-uoa** [comment]
Well since this is still an issue I use the following instead:

`{optionsArray.map((item, index) => {
                    return (
                    <ListItem className="p-0" key={index}>
                    <label
                        htmlFor={item.value}
                        className="flex w-full cursor-pointer items-center px-3 py-2"
                    >
                        <ListItemPrefix className="mr-3">
                            <Checkbox
                                id={item.value}
                                value={item.value}
                                checked={item.isSelected}
                                onChange={(e) => handleOnChange(e, index)}
                                ripple={false}
                                className="hover:before:opacity-0"
                                containerProps={{
                                    className: "p-0",
                                }}
                            />
                        </ListItemPrefix>
                        <Typography color="blue-gray" className="font-medium">
                                {item.value}
                        </Typography>
                    </label>
                    </ListItem>
                        )
                })}`

**Comment by Mohannad35** [comment]
I have the same issue and this solution ([Solution by Roza](https://stackoverflow.com/a/76488478/16811621)) works for me but you can't change the value by changing setState of the value

**Comment by kenzaflow** [comment]
> I have the same issue and this solution ([Solution by Roza](https://stackoverflow.com/a/76488478/16811621)) works for me but you can't change the value by changing setState of the value

sure, but the component would not be controlled

**Comment by sajadevo** [comment]
Guys I've implemented this example for dynamic option and select please give it a try.

```jsx
import React from "react";
import { Select, Option } from "@material-tailwind/react";

const VALUE_OPTIONS = [
  {
    value: "html",
    label: "Material Tailwind HTML",
  },
  {
    value: "react",
    label: "Material Tailwind React",
  },
  {
    value: "vue",
    label: "Material Tailwind Vue",
  },
];

const REACT_VALUE_OPTIONS = [
  {
    value: "next",
    label: "Next.JS",
  },
  {
    value: "remix",
    label: "Remix",
  },
];

export default function SelectDefault() {
  const [value, setValue] = React.useState("html");
  const [reactValue, setReactValue] = React.useState("next");

  return (
    <div className="w-72">
      <Select
        value={value}
        onChange={(value) => setValue(value)}
        label="Select Version"
      >
        {VALUE_OPTIONS.map(({ value, label }) => (
          <Option key={label} value={value}>
            {label}
          </Option>
        ))}
      </Select>

      <div className="mt-16">
        {value === "react" && (
          <Select
            value={reactValue}
            onChange={(value) => setReactValue(value)}
            label="Select React Framework"
          >
            {REACT_VALUE_OPTIONS.map(({ value, label }) => (
              <Option key={label} value={value}>
                {label}
              </Option>
            ))}
          </Select>
        )}
      </div>
    </div>
  );
}
```

@kenzaflow lemme know if it's still not fixing your issue, maybe you can share your entire code with me so that I can check it.

**Comment by RenaldiPranata** [comment]
any update?

**Comment by RenaldiPranata** [comment]
Here is the fixed code that works fine.

```javascript
 <Controller
    control={hook.control}
    name={'competency'}
    rules={{required: true}}
    render={({field, fieldState}) => (
        <Select
            value={field.value}
            onChange={(value) => field.onChange(value)}
            selected={() => {
                return field.value;
            }}
            ref={field.ref}
            error={fieldState.error ? true : false}
            label='Competency'
        >
            {hook.competencyDictionary
                .filter((item) => item.family === family_competency)
                .toArray.flatMap((item) => item.competency)
                .map((item, index) => (
                    <Option
                        key={`key-${index}`}
                        value={item.name}
                    >
                        {item.name}
                    </Option>
                ))}
        </Select>
    )}
/>
```

**Comment by pinguks** [comment]
this is my current solution:

`import { uniqueId } from "lodash";
import React, { useEffect, useState } from "react";
import { Select, SelectProps } from "@material-tailwind/react";

const AsyncSelect = React.forwardRef((props: SelectProps, ref: any) => {
  const [key, setKey] = useState("");

  useEffect(() => setKey(uniqueId()), [props]);

  return <Select key={key} ref={ref} {...props} />;
});

AsyncSelect.displayName = "AsyncSelect";

export default AsyncSelect;
`

**Comment by inkinkz** [comment]
> this is my current solution:
> 
> ```
> import { uniqueId } from "lodash";
> import React, { useEffect, useState } from "react";
> import { Select, SelectProps } from "@material-tailwind/react";
> 
> const AsyncSelect = React.forwardRef((props: SelectProps, ref: any) => {
>   const [key, setKey] = useState("");
> 
>   useEffect(() => setKey(uniqueId()), [props]);
> 
>   return <Select key={key} ref={ref} {...props} />;
> });
> 
> AsyncSelect.displayName = "AsyncSelect";
> 
> export default AsyncSelect;
> ```

Thank you

**Comment by kenzaflow** [comment]
> We have the same issue in our app too and some of our dynamic selects work and others don't. It's so bad we have contemplated building our own select component that looks identical for now.

At the end, I also followed this path. I got rid of this library (many bugs, bad implementation of TypeScript, so forking was not an option), and we made the components from scratch, with only what was necessary.

I'm closing this because it looks like they found solutions.
