### ISSUE TITLE
Nextjs, server components

### ISSUE THREAD

**Issue by GeekyChunk** [creativetimofficial/material-tailwind#424]
#### I wish there was any way to use it in server component which is very effective in case of SEO

```2 | import { useLayoutEffect, useEffect, useRef } from 'react';
 3 | import { hideOthers } from 'aria-hidden';
 4 | import { tabbable } from 'tabbable';
 5 | import { createPortal, flushSync } from 'react-dom';
   :                        ^^^^^^^^^
 6 | import { getOverflowAncestors, offset, detectOverflow, useFloating as useFloating$1 } from '@floating-ui/react-dom';
 7 | export { arrow, autoPlacement, autoUpdate, computePosition, detectOverflow, flip, getOverflowAncestors, hide, inline, limitShift, offset, platform, shift, size } from '@floating-ui/react-dom ```

**Comment by aliemami-coder** [comment]
Hi,
you can wrap the Material Tailwind component in other components and add `use client` to the first line of the file.

example:
create a file with MTCustom.tsx (or jsx) and use this code:

```
"use client";
 
import { ThemeProvider, Button } from "@material-tailwind/react";
 
export { ThemeProvider, Button };
```

use Button or ThemeProvider in other files:

`import "/styles/globals.css";
 
import { ThemeProvider } from "./path/to/MTCustom";
 
export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}`

[https://www.material-tailwind.com/docs/react/guide/next](https://www.material-tailwind.com/docs/react/guide/next)
