### ISSUE TITLE
Not able to jump on the desired docs page

### ISSUE THREAD

**Issue by SachinCoder1** [creativetimofficial/material-tailwind#433]
I forked the main branch and i want to contribute to the material tailwind... 

but after forking **how can i go to the docs page**?.. currently it is showing 404 no page found in the localhost but the same path works on the main website ? 

how can i go to this page in localhost ?
https://www.material-tailwind.com/docs/react/popover

(check url in these screenshots)
![image](https://github.com/creativetimofficial/material-tailwind/assets/98685642/3f041ad8-928d-4793-8280-cabb8ef6cd20)
![image](https://github.com/creativetimofficial/material-tailwind/assets/98685642/b24f2d9a-6937-404c-80ed-e8450e0d978d)
![image](https://github.com/creativetimofficial/material-tailwind/assets/98685642/39afcca3-af19-4fc4-9091-2d9b6d29dd34)

**Comment by renny-ren** [comment]
It shows correctly in my localhost...
Did you run `pnpm i`? any errors showing on the terminal?

**Comment by SachinCoder1** [comment]
No errors in terminal.. i checked.. 

Obviously i run pnpm i that's why the main page is running perfectly.. 

Which branch are you using ? Is there any configuration or something you did initially ?

**Comment by SachinCoder1** [comment]
@timcreative @alexandru-paduraru @marqbeniamin 

Can you help ?

**Comment by muhiddinjv** [comment]
I have the same exact problem. I was going to fix something on https://www.material-tailwind.com/docs/react/installation but I can't go to this page in http://localhost:3000/docs/react/installation. 
![image](https://github.com/creativetimofficial/material-tailwind/assets/50528874/d3770a75-9d59-4205-9bae-f9bdfc55953f)

**Comment by sajadevo** [comment]
@SachinCoder1,
It's weird because it works just fine for me no 404 page could you please tell me which steps you've did after cloning the project and which branch you've cloned?

**Comment by muhiddinjv** [comment]
1. cloned the main branch
2. pnpm i
3. pnpm dev
I then switched to dev-main branch but there I got the 404 page too

**Comment by SachinCoder1** [comment]
@sajadevo 

exact steps i followed : 

1. cloned the main branch
2. pnpm i
3. pnpm dev

this is all i did and after the server started i gone to the desired docs page but then it was showing 404 not found page..

Is there any other configuration or something i have to do ?

**Comment by code-cola-js** [comment]
I also have the same issue. The homepage can be opened, but /docs cannot.
![image](https://github.com/creativetimofficial/material-tailwind/assets/64840669/9e56cf72-d59b-4d80-b539-1bbddacaa390)
node v16.14.0
windows 10
branch dev-main

**Comment by pratikwaware** [comment]
Hi @SachinCoder1  have you resolved this issue ? I am having the same issue.
![image](https://github.com/creativetimofficial/material-tailwind/assets/48583769/ce608c0b-45b5-4a2a-9d65-c242bdb6149e)

**Comment by sinkovmikhail** [comment]
I have some issue, either. Anyone who can help?
