### ISSUE TITLE
How to override animation transition duration

### ISSUE THREAD

**Issue by armandleopold** [creativetimofficial/material-tailwind#436]
It seems we can't override animation duration from material-tailwind components;
Is that right or am i missing something ?

**Comment by sajadevo** [comment]
Hey @armandleopold,
You can change the duration for animations in Material Tailwind, this is the way you can do it.

```jsx
<Component animate={{
  mount: {
    transition: { duration: 0.2 },
  },
  unmount: {
    transition: { duration: 0.4 },
  },
}} />
```

**Comment by armandleopold** [comment]
Thanks @sajadevo  !
