### ISSUE TITLE
<Select > and <Option> Components with react-hook-form

### ISSUE THREAD

**Issue by NadjimAttm** [creativetimofficial/material-tailwind#445]
`<Select
      label="role"
      size="lg"
      variant="standard"
      error={errors.role?.message}
      {...register('role')}
    >
      {jobstList?.map((post) => (
        <Option key={post.name} value={post.value}>
          {post.name}
        </Option>
      ))}
 </Select>`

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at onChange (createFormControl.ts:658:1)
    at handleSelect (SelectOption.js:1:1)
    at onClick (SelectOption.js:1:1)
    at floating-ui.react.esm.js:3331:1
    at Array.forEach (<anonymous>)
    at acc.<computed> (floating-ui.react.esm.js:3331:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)

**Comment by chuysb** [comment]
Confirm your post hast a name property with a console.log.

**Comment by Ebinsha** [comment]
Hi the same error is happening for me as well.

**Comment by Ebinsha** [comment]
Can you please update how you solved ?

**Comment by NadjimAttm** [comment]
> Can you please update how you solved ?

the register funcoutside the select element and add props name, onBlur, ref in select element

..................
 const { name, ref, onBlur } = register('role', {
    required: {
      value: true,
      message: 'Field is required"',
    },
  })
  ..............

 <Select
                    label="role"
                    size="lg"
                    variant="standard"
                    error={!!errors.role?.message}
                    onChange={handleSelectChange}
                    name={name}
                    ref={ref}
                    onBlur={onBlur}
                  >
                    {jobstList?.map((post) => (
                      <Option key={post.name} value={post.value}>
                        {post.name}
                      </Option>
                    ))}
                  </Select>
