### ISSUE TITLE
Input not working z-index 

### ISSUE THREAD

**Issue by amirainfo** [creativetimofficial/material-tailwind#451]
Hi team , good day.

I have a code with a div and a Input inside. When I run in the browser in my phone , the Input stay in a front of all elements even more of the DIV.

The code is here:
![error1](https://github.com/creativetimofficial/material-tailwind/assets/41497548/34c64c0b-c943-407d-ba44-9ae9ce53a4e6)

Could you please help me about this ?

 <div className="flex flex-col h-14 w-7/12 p-0 ml-1 pt-0 mr-0 rounded-md relative border-0 border-red-500">
        
          <Input className="absolute z-[0]"
            onChange={(e) => setQuery(e.target.value)}
            color="red"
            label="Pesquisar"
            size="md"
            
          />
        
      </div>
![erro2](https://github.com/creativetimofficial/material-tailwind/assets/41497548/d8e61fb9-5949-4290-9cac-3efdbe3977e6)

**Comment by shaikahmadnawaz** [comment]
Add more z-index number to side bar.

**Comment by amirainfo** [comment]
@shaikahmadnawaz  , Thanks for support . Now it's working ...

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz , Thanks for support . Now it's working ...

No mention @amirainfo
