### ISSUE TITLE
Popups not don't appear in open dialog due to z index of the dialog being greater than the popup

### ISSUE THREAD

**Issue by Conrad6** [creativetimofficial/material-tailwind#467]
I'm trying to use a Menu component from within a Dialog component. Popups not don't appear in open dialog due to z index of the dialog being greater than the popup

![image](https://github.com/creativetimofficial/material-tailwind/assets/23273191/82de6fa5-af23-4f6c-934e-7a7e9e5b7069)
Above is the image of the dialog instance's markup whose `z-index` is set to 9999 by default

![image](https://github.com/creativetimofficial/material-tailwind/assets/23273191/de3b7745-e5f0-44c2-900f-3722e4cd708e)
Above is the image of the popup related to the Menu instance whose `z-index` is set to 999 by default.

How can one modify the `z-index` property of either of them?

**Comment by trananhthi** [comment]
you can set z-99999 into MenuList 
![image](https://github.com/creativetimofficial/material-tailwind/assets/75987751/ef7547d3-f1b0-493a-9a8d-22b08c5a9fb5)

**Comment by conradbekondo** [comment]
@trananhthi Thanks 👍

**Comment by SkylerB1** [comment]
@trananhthi Do we have to add this to every popup. Isn't there is any other way?
