### ISSUE TITLE
Does it work with nextjs?

### ISSUE THREAD

**Issue by Kublick** [creativetimofficial/material-tailwind#48]
Tried to test it out in Next Js

Installed using:
yarn add @material-tailwind/react -E

on _app.js 
added:
import "@material-tailwind/react/tailwind.css";

Below code should display a white square in the center of the page with a gray background.
```
<div className="flex flex-col justify-center min-h-screen bg-gray-100">
  <div className="sm:mx-auto">
	<div className="p-20 bg-white rounded-lg shadow-lg" />
  </div>
</div>
```
The square wont show.

Vertical centering will not trigger even following the login example classes used.

**Comment by Kublick** [comment]
I had missing the utility classes in global.css it works now :D

**Comment by oshimayoan** [comment]
Hey @Kublick, did you have missing classes when deployed to production by any chance?
