### ISSUE TITLE
Document for react radio - page not found.

### ISSUE THREAD

**Issue by zummon** [creativetimofficial/material-tailwind#491]
at url https://www.material-tailwind.com/docs/react/radio#radio

**Comment by JuanAntonioV** [comment]
did u mean this? [Radio Button Docs](https://www.material-tailwind.com/docs/react/radio-button)

**Comment by zummon** [comment]
i was browsing around react stuff and realized it happened to be html only for radio then i changed to be react, it got 404 not found page.
Right now it looks okey. Thanks maybe i was wrong.
