### ISSUE TITLE
Interactive tooltip not working

### ISSUE THREAD

**Issue by francescocretti** [creativetimofficial/material-tailwind#497]
Hi everyone,
I need to make the tooltip interactive in order to allow the user to click a link.

Here's my code:

```javascript
<Tooltip
  content={
    <div>
      <Typography>Some explanation</Typography>
      <Link
        target='_blank'
        to="link.to.documentation"
      >
        More info here
      </Link>
    </div>
  }
  placement="right"
  interactive
>
  <span>
    <PiInfoLight className='text-primary' />
  </span>
</Tooltip>
```

However when passing the mouse on the tooltip content, it disappears.
Am I doing something wrong?

Packages versions:
* `"@material-tailwind/react": "^2.0.1"`
* `"react": "^18.2.0"`
* `"tailwindcss": "^3.3.2"`

Thanks in advance

**Comment by AbhishekAK411** [comment]
Hi francescocretti,

In the material tailwind documentation, you can find the tooltip props that can be used for this. You can combine a state with the "open" prop to provide the interactivity.
Another easy way is to provide event handlers to the content object.

**Comment by francescocretti** [comment]
Hi @AbhishekAK411, thanks for your answer. 
So, if I got this right, I need to manually manage the `open` property with a state?

**Comment by AbhishekAK411** [comment]
In your case, the interactive property is used to provide functionality to the tooltip that you desire. For example, if you use react-router-dom, you can provide a route to another component as per your specifications.

interactive is by default has a value of "undefined", but is eventually a boolean. If you feed a value of "true", then the tooltip can receive user interactions, like clicks or any other events, or in your case, a route to another page.

**Comment by AbhishekAK411** [comment]
hi @francescocretti is the issue resolved?

**Comment by francescocretti** [comment]
Hi @AbhishekAK411 , yes you can consider it solved.
I just think you should mention in the documentation that to make the you tooltip actually interactive you should manage the state yourself :)

Thanks for your support in any case!

**Comment by AbhishekAK411** [comment]
Hi @francescocretti, I will make a PR for the documentation part. The tooltip documentation should actually provide the interactivity prop as well in a detailed manner, but yes for the time being, we are supposed to manage the state.

You welcome if your issue got resolved 💯 .
btw, can you close this issue from your side?

**Comment by francescocretti** [comment]
Sure! Thanks
