### ISSUE TITLE
Overide ClassName for Modal Component

### ISSUE THREAD

**Issue by dgan181** [creativetimofficial/material-tailwind#51]
It seems the I can overide the `className` prop for every other component except Modals. I am trying to position the modal at the bottom of the screen and change the background colour.

**Comment by sajadevo** [comment]
**Hi Dgan**
Thanks for using Material Tailwind, currently Material Tailwind is not on its stable versions and components don't have any theme provider for more customizations we have the className props for some of the components not at all and we will take care of that on the next version of Material Tailwind.

**Comment by oshimayoan** [comment]
Hi @sajadevo, thanks for the info. Do you have any estimation of when is the next version coming out?

**Comment by gauravadhikariitfaq** [comment]
Any update on this ?

**Comment by sajadevo** [comment]
**Hi guys**

I'm currently working on the official version of Material Tailwind v1.0.0 and this time it will be totally something new and interesting for you, also I should mention that with the official react version the html version will be also released.
Probably the new version will be available within one or two months.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
