### ISSUE TITLE
Dropdown icon is showing as text

### ISSUE THREAD

**Issue by DanDev95** [creativetimofficial/material-tailwind#52]
Copied the example from the docs

Got this

![image](https://user-images.githubusercontent.com/76797800/123665089-3db56b80-d838-11eb-913b-5f59ba6adf3b.png)

**Comment by sajadevo** [comment]
**Hi Dan**

Thanks for using Material Tailwind its because you don't add the link of the material icons to your project.
Just add this link to the head of your app: `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>`
