### ISSUE TITLE
Lower case text for buttons ?

### ISSUE THREAD

**Issue by bp289** [creativetimofficial/material-tailwind#532]
Is there a way to make the text on buttons lower case? 
In the documentation all examples show the text being in upper case.
![image](https://github.com/creativetimofficial/material-tailwind/assets/100142251/e5444b28-9cd4-44f6-ba84-6a568af61827)

**Comment by don-esteban** [comment]
Simply use Tailwind utilities.

**Comment by bp289** [comment]
Ended up going with that in the end, Thanks!

**Comment by bp289** [comment]
> what if I want both upper and lower case? For example `Click Me!`

I think it should work with tailwinds ["capitalize" ](https://tailwindcss.com/docs/text-transform) ?

e.g: 
` <Button className="capitalize ...">Click Me!</Button>`
