### ISSUE TITLE
tabs are not responsive

### ISSUE THREAD

**Issue by Shifath472533** [creativetimofficial/material-tailwind#54]
The tabs are not responsive. It moves out of the screen.

**Comment by Shifath472533** [comment]
The tabs are not responsive.

**Comment by sajadevo** [comment]
Hi @Shifath472533 

I've updated @material-tailwind/react and now tabs are more flexible and scalable also its totally responsive, please check the [Tabs](https://www.material-tailwind.com/docs/react/tabs) component docs for a better understanding.

All the best,
Sajad
