### ISSUE TITLE
Components requesting placeholder prop after the latest update

### ISSUE THREAD

**Issue by ishahbaz7** [creativetimofficial/material-tailwind#547]
After the latest update, several components in Material Tailwind are now requiring a placeholder prop. This was not the case in previous versions. Developers are prompted to provide a placeholder prop where it wasn't required before.

Steps to Reproduce:

Configure Material Tailwind with React Typescript
Utilize components that previously did not require a placeholder prop.
Observe the error or warning prompting for a placeholder prop.

Expected Behavior:
Components should function as intended without the need for a placeholder prop, as per previous versions.

Environment:

Material Tailwind version: 2.1.8
React version: 18

**Comment by ishahbaz7** [comment]
I

> Duplicate. See just a few issues below or a simple search: #528
> 
> ```
> npm install @types/react@18.2.42  // resolves all, but "Property 'crossOrigin' is missing" in Input.
> npm install @types/react@18.2.18  // resolves all.
> ```

Thanks don-esteban. Its works.

**Comment by frankdavid-addae** [comment]
I was using @types/react@18.2.42 and all of a sudden this issue came up again, and I have to downgrade to @types/react@18.2.18.
Does that means this issues is still not resolved in latest versions of @types/react?
