### ISSUE TITLE
Add inputRef support

### ISSUE THREAD

**Issue by njahncke-megaphone** [creativetimofficial/material-tailwind#55]
First off, great library! Thanks a lot for all your hard work. I would PR this fix myself, but I'm not familiar enough with React yet.

## Expected Behavior

Standard Material UI Components allow for the passing of refs via the `inputRef` prop. The Material Tailwind version should as well.

## Current Behavior

If you add a ref via `inputRef` to a Material Tailwind Input Component, you receive the following error: `"Warning: React does not recognize the inputRef prop on a DOM element."`.

## Possible Solution

Unfortunately, I'm not sure how to solve this issue.

## Steps to Reproduce (for bugs)

1. Create reference using `useRef()`.
2. Add reference as `inputRef` prop to `<Input>` Component.

## Context

The goal here is to allow a hotkey to focus the input in question. There are workarounds, but given this is a deviation from the expected behavior of Material Components, I believe everyone would appreciate a fix.

## Your Environment

`"react": "^17.0.2",`
`"@material-tailwind/react": "0.3.4",`

**Comment by msreekm** [comment]
Created a PR for this https://github.com/creativetimofficial/material-tailwind/pull/57.

**Comment by sajadevo** [comment]
Hi guys,

I've updated @material-tailwind/react and now each component can get a ref.

All the best,
Sajad
