### ISSUE TITLE
icon font family property not working : family="font-awesome"

### ISSUE THREAD

**Issue by lemarcgagnon** [creativetimofficial/material-tailwind#56]
## Expected Behavior

I was expecting the Icon.js module to be able to use the family property with the " "family: 'font-awesome' " not  " family: 'material-icons' "

## Current Behavior for material-tailwind-dashboard-react-main > Component > Setting.js 

 <StatusCard
                            color="pink"
                            family="font-awesome"
                            icon="fa-camera"
                            title="Traffic"
                            amount="350,897"
                            percentage="3.48"
                            percentageIcon="arrow_upward"
                            percentageColor="green"
                            date="Since last month"
                        />

it always uses the default setting for material-icons

Icon.defaultProps = {
  family: 'material-icons',
  size: 'base'
};

## Possible Solution 

to make it work I had to modify 

Icon.defaultProps = {
  family: 'font-awesome',
  size: 'base'
};

 in
node_modules > @material-tailwind > react >Icon.js line 81 otherwise I can not use fontawesome

then I restarted the app for it to be effective

## Your Environment

yes my public > index.html includes these lines

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
      integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
      crossorigin="anonymous"
    />

- Version used: 14
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Linux
- Link to your project: localhost only... sorry

**Comment by sajadevo** [comment]
Hi @lemarcgagnon 

I've updated @material-tailwind/react and now you can use any type of icon fonts you want.

All the best,
Sajad
