### ISSUE TITLE
Does not getting value from Select Option component like html core select option in form 

### ISSUE THREAD

**Issue by rezzakali** [creativetimofficial/material-tailwind#560]
I am using Select Option componet of MT. I have a form with an Input field and a Select Option to choose gender, If I use state then okay, But I am using it with react server action , where I get formData,when i console it then getting only input's value not gender.
Here is my code below.
![code](https://github.com/creativetimofficial/material-tailwind/assets/87976069/2477d4a5-0c43-408e-8654-e3e69dfc51be)

**Comment by sajadevo** [comment]
Hey @rezzakali the select component is not working with server actions and it doesn't support in `formData` we'll have it in the new version of material tailwind react v3.

**Comment by rezzakali** [comment]
Okay
