### ISSUE TITLE
For a Select component with the outlined variant, the outline has a break in it when there is no label

### ISSUE THREAD

**Issue by jlutteringer** [creativetimofficial/material-tailwind#578]
When using a select like so:
```
  <Select variant="outlined">
    <Option>Material Tailwind HTML</Option>
    <Option>Material Tailwind React</Option>
    <Option>Material Tailwind Vue</Option>
    <Option>Material Tailwind Angular</Option>
    <Option>Material Tailwind Svelte</Option>
  </Select>
```

There is a break in the top border where the label is supposed to go - but there is no label present. This is because there is a margin applied to the :before and :after pseudo elements which construct the top of the component's border around the label. This margin still gets applied in circumstances where there is no label - resulting in a break in the border.

There is a sort of workaround by using the theme system to remove the margins, but this means that whenever you DO have a label, the border runs right into the label text.

Here's an example of what it looks like:
<img width="396" alt="Screenshot 2024-02-01 at 11 43 10 AM" src="https://github.com/creativetimofficial/material-tailwind/assets/2106323/74f967b7-ca12-4a6b-81cb-a89b8ac1c787">

**Comment by jlutteringer** [comment]
For the record, this same issue also applies to Input elements

**Comment by sajadevo** [comment]
@jlutteringer the label is required for each input, select and textarea components and if you want to have them without label you need to provide some set of custom styles for each component, check the link below for an example of input component without label
https://www.material-tailwind.com/docs/react/input#input-custom-styles
