### ISSUE TITLE
Change Dropdown buttonText

### ISSUE THREAD

**Issue by blanktix** [creativetimofficial/material-tailwind#58]
How can we change the buttonText with selected dropdown items? Should we use useEffect in every dropdown components to handle change?

**Comment by sajadevo** [comment]
Hi @blanktix 

I've updated @material-tailwind/react and now the Dropdown component has changed to Menu component with more flexibility and scalability, please check the docs for the [Menu](https://www.material-tailwind.com/docs/react/menu) component.

All the best,
Sajad
