### ISSUE TITLE
Add Icon to dropdown

### ISSUE THREAD

**Issue by ExordiumX** [creativetimofficial/material-tailwind#63]
How do I add an icon to the dropdown component? You seem to have done this somehow on the documentation site at the header, but I can't figure out how.

**Comment by rutulganatra** [comment]
@DanDev95 Can you assign this task under hactoberfest label and which page you want to add icon in dropdown component?

**Comment by kaspnilsson** [comment]
Do it like this, @DanDev95: https://github.com/creativetimofficial/material-tailwind/blob/fef387df3ff87cd0fb911efa5e5c6f17f3c7850e/components/Documentation/Navbar.js#L57

**Comment by sajadevo** [comment]
Hi guys,

I've updated @material-tailwind/react and now the dropdown changed to Menu component with more flexibility and scalability [Menu](https://www.material-tailwind.com/docs/react/menu).

All the best,
Sajad
