### ISSUE TITLE
TypeScript Error: Props Missing on Material-Tailwind Components

### ISSUE THREAD

**Issue by drokbers** [creativetimofficial/material-tailwind#664]
Hi,

I've encountered an issue with the latest version of the Material-Tailwind library where TypeScript throws errors indicating that certain props are missing from the components, even when using them as documented. According to the TypeScript errors, props such as `placeholder`, `onPointerEnterCapture`, and `onPointerLeaveCapture` are missing from components like `Typography`, `Button`, `Card`, and `TabsHeader`.

I tried versions 2.1.9 and 2.1.4

For instance, when using the `Typography` component like so:
```
tsx
<Typography className="my-5 font-normal !text-gray-600">
text
</Typography>
```

TypeScript expects props that aren't typically required or documented, resulting in the following error:

`Type '{ children: string; className: string; }' is missing the following properties from type 'Pick<TypographyProps, "id" | "children" | ... >': placeholder, onPointerEnterCapture, onPointerLeaveCapture`

This issue is not isolated to Typography but extends to other components such as Button, Card, and TabsHeader, suggesting a broader issue with the TypeScript type definitions within the library.

Normally, these components don't require additional props for basic usage, as per the official documentation. This leads me to believe there might be an issue with the type definitions provided.

Could you please look into this? It's possible that the TypeScript definitions might need to be updated to reflect the actual required props for these components or to mark these additional props as optional if they are not intended to be mandatory.

**Comment by drokbers** [comment]
changing types/react version with "18.2.42", solve the problem

**Comment by drokbers** [comment]
changing types/react version with "18.2.42", solve the problem

**Comment by lukewealth** [comment]
Thanks for this. it worked

**Comment by jeevankc17** [comment]
No no its not working there is no issue but the warning  is still there
![image](https://github.com/creativetimofficial/material-tailwind/assets/62981718/d4c8f745-f838-4c65-afea-72a1546d30f3)
![image](https://github.com/creativetimofficial/material-tailwind/assets/62981718/aa0a143c-b6d9-40d6-a80d-a0de5e64b5bc)

**Comment by drokbers** [comment]
> No no its not working there is no issue but the warning is still there ![image](https://private-user-images.githubusercontent.com/62981718/325145782-d4c8f745-f838-4c65-afea-72a1546d30f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwODQ1NTEsIm5iZiI6MTcxNDA4NDI1MSwicGF0aCI6Ii82Mjk4MTcxOC8zMjUxNDU3ODItZDRjOGY3NDUtZjgzOC00YzY1LWFmZWEtNzJhMTU0NmQzMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIyMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTVjODc2ZGExM2RhMzRlYzk1YTlhMDQ4MzRhMDQ0ZjAwYTI1NTUzMTRlZDI1YTUzODIzYmE5YjliOTcwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXFbq-9C-9Ui_TAOU_Mrm8Hy1LlnVUDLzUoiZcdoTEs) ![image](https://private-user-images.githubusercontent.com/62981718/325145791-aa0a143c-b6d9-40d6-a80d-a0de5e64b5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwODQ1NTEsIm5iZiI6MTcxNDA4NDI1MSwicGF0aCI6Ii82Mjk4MTcxOC8zMjUxNDU3OTEtYWEwYTE0M2MtYjZkOS00MGQ2LWE4MGQtYTBkZTVlNjRiNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIyMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZjBmODgwY2UwMWNlNTRhNjc5Mzg5OGY1MTcxYmI5MDcwMzBjMjY4NTJhMmVmMmNmMzc1MWE1YTAxZWQ0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCtIsMnB-8A2htGYL_pzhKlxn5I6viu6IDhRIphPP-E)


```
 "@material-tailwind/react": "^2.1.4",
"next": "v13.5.7-canary.25",
 "react": "^18",
    "react-dom": "^18",
 "devDependencies": {
    "@types/jsonwebtoken": "^9.0.4",
    "@types/node": "^20",
    "@types/react": "18.2.42",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "eslint": "^8",
    "eslint-config-next": "13.5.6",
    "postcss": "^8",
    "tailwindcss": "^3",
    "typescript": "^5"
  }
```
