### ISSUE TITLE
[feature request] change progress percentage label/text

### ISSUE THREAD

**Issue by shierro** [creativetimofficial/material-tailwind#67]
## Expected Behavior

If possible, change the label "Completed" in progress bar, percentage = true

## Current Behavior

No API yet to edit this

## Possible Solution

```
<Progress
  color="lightGreen"
  value="100"
  percentage={true}
  percentageLabel="Compressed" # suggestion
/>
```

## Your Environment

- Version used: 1.0.7
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): desktop
- Link to your project:

**Comment by Bhavin789** [comment]
HI @shierro, is this is being worked upon? If not, mind if I give it a try? Thanks!!

**Comment by shierro** [comment]
Haven't worked on it yet and of course you can 😄

**Comment by sajadevo** [comment]
Hi guys,

I've just updated the @material-tailwind/react and fix this issue.

All the best,
Sajad
