### ISSUE TITLE
add select input

### ISSUE THREAD

**Issue by ZE-BOSS** [creativetimofficial/material-tailwind#69]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by sajadevo** [comment]
**Hi** @ZE-BOSS 

Thanks for using Material Tailwind we will take care of the new component on the next updates of Material Tailwind.

**All the best**
**Sajad**
