### ISSUE TITLE
Spam in Documentation

### ISSUE THREAD

**Issue by James-Wilkinson-git** [creativetimofficial/material-tailwind#695]
https://github.com/creativetimofficial/material-tailwind/blob/a318436ecab2abfe6986c9e32b4fed8007b78014/documentation/react/navbar.mdx?plain=1#L411

This isn't relevant to the page.

**Comment by abdulbasithqb** [comment]
> https://github.com/creativetimofficial/material-tailwind/blob/a318436ecab2abfe6986c9e32b4fed8007b78014/documentation/react/navbar.mdx?plain=1#L411
> 
> This isn't relevant to the page.

i think so

**Comment by sajadevo** [comment]
@James-Wilkinson-git it is, it's used for sticky navbar example.
