### ISSUE TITLE
How to go past this error 

### ISSUE THREAD

**Issue by luigimorel** [creativetimofficial/material-tailwind#701]
I've never installed this package and not had an error and most times I've ditched it. But I'd like to give it a try and if the maintainers were responsive, I'd gladly fix some of the bugs but they're not. 

This is what I'm faced with 
![image](https://github.com/creativetimofficial/material-tailwind/assets/48476293/e01f2408-ded3-4ad7-8702-109c896cc212)

**Comment by willfolsom** [comment]
Try `placeholder={''}`

**Comment by dev-phantom** [comment]
this is a typescript the problem is in the new versions of @react/types package 

kindly use this [stackoverflow answer](https://stackoverflow.com/questions/78296875/typescript-error-using-material-tailwind-react-with-nextjs14) to solve the error
