### ISSUE TITLE
Error with color white in Textarea component

### ISSUE THREAD

**Issue by joshtin2505** [creativetimofficial/material-tailwind#705]
It only gives that error with that color

![31dd96ce-af1a-41ed-8f10-7dcff6ab5454](https://github.com/creativetimofficial/material-tailwind/assets/91860458/7f69f2a2-d227-4ec8-a161-5522e6402b2f)
![a9bc1b05-6653-432c-9647-b33624ce160c](https://github.com/creativetimofficial/material-tailwind/assets/91860458/9c143f24-e1e4-4fa1-abc6-b5048637e72e)

**Comment by sajadevo** [comment]
@joshtin2505 thanks for reporting this issue I've fixed that on v2.1.10.
