### ISSUE TITLE
Scroll issue in sidebar 

### ISSUE THREAD

**Issue by RijoKsd** [creativetimofficial/material-tailwind#708]
In my laptop view, I can't scroll to view all sidebar options. I can only view up to the heading of customization. When I zoom out my browser, I am able to see some contents of  components  .

**Comment by dev-phantom** [comment]
yea noticed it 

here is a temporary fix click on **customization** then use your down arrow key on your keyboard to scroll down

**Comment by sajadevo** [comment]
@RijoKsd could you please tell me which resolution is your screen because, I've tested that on different screen sizes but didn't got this issue.

**Comment by RijoKsd** [comment]
@sajadevo Now there is no scroll issue, I think they fixed it now
