### ISSUE TITLE
Text inside TextArea goes over the placeholder

### ISSUE THREAD

**Issue by Nikola-Milovic** [creativetimofficial/material-tailwind#72]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior

Text should be padded somehow not to go over the placeholder when scrolled but rather always stay below it

## Current Behavior

Text clips the upper boundary of text area and it just looks bad

## Steps to Reproduce (for bugs)

![image](https://user-images.githubusercontent.com/50072027/147054502-15f8487c-6e60-456b-95a3-44273bec20cc.png)

**Comment by sajadevo** [comment]
**Hi there**

Thanks for reporting that we will fix that on the next update of the product.

**All the best**
**Sajad**

**Comment by ambitus-dev** [comment]
This bug still exists in material-tailwind/react 2.1.9. I'm using MT with Next 14.1.0

![image](https://github.com/creativetimofficial/material-tailwind/assets/140524761/5c0c3938-3f09-4b51-8dd5-8c20236067ae)

![image](https://github.com/creativetimofficial/material-tailwind/assets/140524761/fb090952-b2c3-4e42-bcac-7087f8f9b42a)
