### ISSUE TITLE
Input Field Unwanted Boder Appered

### ISSUE THREAD

**Issue by Md-Sarfaraz** [creativetimofficial/material-tailwind#78]
Whenever the Input field is in focus, a border appears apart from the variant border style. is there any way to remove or disable it if it is present intentionally as a design? otherwise, if it's a  bug please fix it as soon as possible
by the way, I am using the latest version
```json
  "dependencies": {
    "@material-tailwind/react": "^1.0.3",
  }
```

and my tailwind.config.js file looks like
```js
const withMT = require("@material-tailwind/react/utils/withMT"); 

module.exports = withMT({
  content: ["./src/**/*.{js,jsx,ts,tsx}"],

  theme: { ...  },
  plugins: [],
  });

```

**Comment by sajadevo** [comment]
Hi @Md-Sarfaraz

Thanks for using @material-tailwind/react, we noticed this issue and we will fix it for the next update.

All the best,
Sajad

**Comment by smcenlly** [comment]
I saw the same behavior in Safari but not in Chrome. I believe it can be removed with `outline:none`.

**Comment by sajadevo** [comment]
Hi @Md-Sarfaraz, @smcenlly,

I've updated the @material-tailwind/react and now this issue is fixed for the following components: 
- Input
- Select
- Textarea

All the best,
Sajad
