### ISSUE TITLE
Cannot be used in Vite

### ISSUE THREAD

**Issue by 1739616529** [creativetimofficial/material-tailwind#81]
I want to use it in Vite create react app. But it doesn't work

**Comment by sajadevo** [comment]
Hi @1739616529 

This issue will be fixed on the future update of the product.

All the best,
Sajad

**Comment by sajadevo** [comment]
Hi @mahdi-jafaree 

Yup I know that and already working on it, it's not the only issue we need to make it totally compatible with vite.js and this will definitely happen on the next update of the product.

All the best,
Sajad

**Comment by sajadevo** [comment]
Hi @1739616529, @mahdi-jafaree,

The @material-tailwind/react is updated and now you can use it with vite.js as well.

All the best,
Sajad
