### ISSUE TITLE
Cannot set "for" attribute from labelProps

### ISSUE THREAD

**Issue by Giuseppe7887** [creativetimofficial/material-tailwind#816]
Passing "htmlFor" in labelProps to any input component does not work, the attribute "for" on the label is not set on the effective output lable

**Comment by sajadevo** [comment]
@Giuseppe7887 use the example below to add the `for` attribute for the label element on the input component
```jsx
<Input
  label="Username"
  labelProps={{
    htmlFor: "Username",
  }}
/>
```

**Comment by Giuseppe7887** [comment]
it doesn't work on Textarea
