### ISSUE TITLE
Please Keep Old Documentations Page also.

### ISSUE THREAD

**Issue by Angryman18** [creativetimofficial/material-tailwind#82]
I have been using it for long and also do copy and paste from docs and i suddenly see these are vanished with new docs.

**Comment by ichuoi** [comment]
Agree, should keep both old version

**Comment by sajadevo** [comment]
Hi guys,

Unfortunately we don't provide any support for the old version anymore since it was just a beta version not the initial one, but we will try to find a solution for that so that you can use it.

All the best,
Sajad
